#!/usr/bin/python3
"""JOCO ROBOS CAD server administration: seasons, library, locks, and accounts.

`joco.py ensure` runs at container start. `joco.py serve` is the mentor web page,
listening only inside the container; Apache authenticates users and forwards
/admin with the verified username. Students never need this page.
"""
import fcntl
import hashlib
import hmac
import html
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import xml.etree.ElementTree as ElementTree
from email.parser import BytesParser
from email.policy import HTTP
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, quote, urlsplit

REPOS = os.environ.get('JOCO_REPOS', '/var/lib/svn')
CONFIG = os.environ.get('JOCO_CONFIG', '/etc/joco')
HOOKS = os.environ.get('JOCO_HOOKS', '/opt/joco')
USERS = os.path.join(CONFIG, 'users')
STATE = os.path.join(CONFIG, 'state.json')
AUTHZ = os.path.join(CONFIG, 'authz')
CATALOG = os.path.join(CONFIG, 'public', 'catalog.json')
SECRET = os.path.join(CONFIG, 'admin-secret')
UPDATES = os.path.join(CONFIG, 'public', 'updates')
INSTALLER = re.compile(r'^JOCO-ROBOS-CAD-Setup-(\d{1,4})\.(\d{1,4})\.(\d{1,4})\.exe$')
LIBRARY = 'Library'
# GitHub Actions account: may only stage installers, never touch CAD or the admin pages.
PUBLISHER = 'github-release'
SEASON = re.compile(r'^(19|20)\d{2}-Robot$')
USERNAME = re.compile(r'^[a-z0-9][a-z0-9._-]{1,31}$')
SEGMENT = re.compile(r'^[A-Za-z0-9][A-Za-z0-9 _().&+,-]{0,99}$')
CAD = ('.sldprt', '.sldasm', '.slddrw')
ROBOT_FOLDERS = ['00_Master', '10_Drivetrain', '20_Intake', '30_Shooter', '40_Climber', '50_Electrical', '90_COTS']
LIBRARY_FOLDERS = ['Motors', 'Gearboxes', 'Wheels', 'Electronics', 'Hardware', 'Mechanisms']
MAX_UPLOAD = 100 * 1024 * 1024  # Cloudflare's request limit on the free plan.
_mutex = threading.Lock()


class Refused(Exception):
    """A request that was understood but not allowed; shown to the mentor."""


def run(*args, stdin=None):
    result = subprocess.run(args, input=stdin, capture_output=True)
    if result.returncode != 0:
        raise Refused((result.stderr or result.stdout).decode('utf-8', 'replace').strip() or 'Command failed: ' + args[0])
    return result.stdout.decode('utf-8', 'replace')


class Locked:
    """Serialize changes across web threads and `podman exec` maintenance."""
    def __enter__(self):
        _mutex.acquire()
        self.handle = open(os.path.join(CONFIG, '.admin.lock'), 'w')
        fcntl.flock(self.handle, fcntl.LOCK_EX)

    def __exit__(self, *_):
        fcntl.flock(self.handle, fcntl.LOCK_UN)
        self.handle.close()
        _mutex.release()


def write_atomic(path, text, mode=0o640):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, temp = tempfile.mkstemp(dir=os.path.dirname(path))
    with os.fdopen(fd, 'w') as handle:
        handle.write(text)
    os.chmod(temp, mode)
    os.replace(temp, path)


# ---------- state ----------

def repositories():
    # Dot-folders hold deleted seasons; they are not served or backed up.
    return sorted(n for n in os.listdir(REPOS) if not n.startswith('.') and os.path.isfile(os.path.join(REPOS, n, 'format')))


def load_state():
    try:
        with open(STATE) as handle:
            state = json.load(handle)
    except FileNotFoundError:
        seasons = [n for n in repositories() if SEASON.match(n)]
        state = {'active': seasons[-1] if seasons else None, 'archived': [], 'mentors': []}
    state.setdefault('archived', [])
    state.setdefault('mentors', [])
    return state


def save_state(state):
    write_atomic(STATE, json.dumps(state, indent=2) + '\n')
    publish(state)


def uuid(name):
    return run('svnlook', 'uuid', os.path.join(REPOS, name)).strip()


def publish(state):
    """Regenerate SVN access rules and the catalog the add-in reads."""
    # "~name" = every signed-in account except the release uploader.
    rules = ['# Generated by joco.py from state.json; edit through the admin page.', '[/]', '~%s = rw' % PUBLISHER, '']
    for name in state['archived']:
        rules += ['[%s:/]' % name, '~%s = r' % PUBLISHER, '']
    write_atomic(AUTHZ, '\n'.join(rules))
    seasons = [n for n in repositories() if SEASON.match(n)]
    catalog = {
        'version': 1,
        'active': state['active'],
        'robots': [{'name': n, 'uuid': uuid(n), 'archived': n in state['archived']} for n in seasons],
        'library': {'name': LIBRARY, 'uuid': uuid(LIBRARY)} if LIBRARY in repositories() else None,
        # Newest published student installer; the add-in offers it when it is newer than itself.
        'addin': state.get('addin'),
    }
    write_atomic(CATALOG, json.dumps(catalog, indent=2) + '\n', 0o644)


def install_hooks(name):
    hooks = os.path.join(REPOS, name, 'hooks')
    for hook in ('pre-commit', 'pre-lock', 'pre-unlock'):
        shutil.copyfile(os.path.join(HOOKS, hook), os.path.join(hooks, hook))
        os.chmod(os.path.join(hooks, hook), 0o755)


def create_repository(name, folders, author, message):
    path = os.path.join(REPOS, name)
    if os.path.exists(path):
        raise Refused(name + ' already exists.')
    run('svnadmin', 'create', path)
    install_hooks(name)
    args = ['svnmucc', '--non-interactive', '--username', author, '-m', message, '-U', 'file://' + path]
    for folder in folders:
        args += ['mkdir', folder]
    run(*args)


def ensure():
    """Container start: hooks everywhere, a Library repository, consistent generated files."""
    with Locked():
        if LIBRARY not in repositories():
            create_repository(LIBRARY, LIBRARY_FOLDERS, 'joco-admin', 'Create reusable parts library')
        for name in repositories():
            install_hooks(name)
        if not os.path.exists(SECRET):
            write_atomic(SECRET, secrets.token_hex(32), 0o600)
        state = load_state()
        state['archived'] = [n for n in state['archived'] if n in repositories()]
        save_state(state)


# ---------- repository queries ----------

def youngest(name):
    return int(run('svnlook', 'youngest', os.path.join(REPOS, name)))


def locks(name):
    result, current = [], None
    for line in run('svnadmin', 'lslocks', os.path.join(REPOS, name)).splitlines():
        if line.startswith('Path: '):
            current = {'repo': name, 'path': line[6:]}
            result.append(current)
        elif current and line.startswith('Owner: '):
            current['owner'] = line[7:]
        elif current and line.startswith('Created: '):
            current['created'] = line[9:].split(' (')[0]
    return result


def activity(names, limit=15):
    entries = []
    for name in names:
        root = ElementTree.fromstring(run('svn', 'log', '--xml', '-v', '-l', str(limit), 'file://' + os.path.join(REPOS, name)))
        for entry in root.findall('logentry'):
            entries.append({
                'repo': name, 'rev': int(entry.get('revision')),
                'author': entry.findtext('author') or '', 'date': (entry.findtext('date') or '')[:16].replace('T', ' '),
                'msg': (entry.findtext('msg') or '').strip(),
                'files': [p.text for p in entry.findall('paths/path') if p.get('kind') == 'file'],
            })
    return sorted(entries, key=lambda e: e['date'], reverse=True)[:limit]


def files(name):
    listing = run('svnlook', 'tree', '--full-paths', os.path.join(REPOS, name))
    return [p for p in listing.splitlines() if p and not p.endswith('/') and p.lower().endswith(CAD)]


def users():
    with open(USERS) as handle:
        return sorted(line.split(':', 1)[0] for line in handle if ':' in line)


def clean_path(text):
    parts = [p.strip() for p in text.replace('\\', '/').split('/') if p.strip()]
    if not parts or not all(SEGMENT.match(p) for p in parts):
        raise Refused('Use folder and file names with letters, numbers, spaces, and _ ( ) . & + , - only.')
    return '/'.join(parts)


def add_to_library(entries, author, message):
    """entries: [(library path, local file)]. New files only; changing existing parts needs Edit/Submit."""
    existing = set(run('svnlook', 'tree', '--full-paths', os.path.join(REPOS, LIBRARY)).splitlines())
    args = ['svnmucc', '--non-interactive', '--username', author, '-m', message, '-U', 'file://' + os.path.join(REPOS, LIBRARY)]
    made = set()
    for target, local in entries:
        if not target.lower().endswith(CAD):
            raise Refused(target + ' is not a SOLIDWORKS part, assembly, or drawing.')
        if target in existing or target.lower() in {p.lower() for p in existing}:
            raise Refused(target + ' already exists in the library. Update it with Edit and Submit instead.')
        parts = target.split('/')
        for i in range(1, len(parts)):
            folder = '/'.join(parts[:i])
            if folder + '/' not in existing and folder not in made:
                args += ['mkdir', folder]
                made.add(folder)
        args += ['put', local, target, 'propset', 'svn:needs-lock', '*', target,
                 'propset', 'svn:mime-type', 'application/octet-stream', target]
    run(*args)


# ---------- actions (all run under Locked) ----------

def act(user, form):
    action = form.get('action', '')
    state = load_state()
    if action == 'create-season':
        name = form.get('name', '').strip()
        if not SEASON.match(name):
            raise Refused('Season names look like 2028-Robot.')
        create_repository(name, ROBOT_FOLDERS, user, 'Create canonical robot folders')
        if form.get('activate'):
            state['active'] = name
        save_state(state)
        return 'Created ' + name + '.'
    if action == 'delete-season':
        name = form.get('name', '')
        if name not in repositories() or not SEASON.match(name):
            raise Refused('Unknown season.')
        if name == state['active']:
            raise Refused('Make another season active before deleting ' + name + '.')
        # Only a season nobody has submitted to: revision 1 is the folder creation.
        if youngest(name) > 1 or locks(name):
            raise Refused(name + ' has CAD history, so it cannot be deleted. Archive it instead.')
        stamp = time.strftime('%Y%m%dT%H%M%SZ', time.gmtime())
        os.rename(os.path.join(REPOS, name), os.path.join(REPOS, '.deleted-%s-%s' % (name, stamp)))
        state['archived'] = [n for n in state['archived'] if n != name]
        save_state(state)
        return 'Deleted empty season ' + name + '.'
    if action in ('activate', 'archive', 'unarchive'):
        name = form.get('name', '')
        if name not in repositories() or not SEASON.match(name):
            raise Refused('Unknown season.')
        if action == 'activate':
            if name in state['archived']:
                raise Refused('Unarchive ' + name + ' before making it active.')
            state['active'] = name
        elif action == 'archive':
            if name == state['active']:
                raise Refused('Make another season active before archiving ' + name + '.')
            if locks(name):
                raise Refused(name + ' still has locked files. Ask students to Submit, or release the locks first.')
            state['archived'] = sorted(set(state['archived']) | {name})
        else:
            state['archived'] = [n for n in state['archived'] if n != name]
        save_state(state)
        return {'activate': 'Students now open ' + name + '.', 'archive': name + ' is read-only.', 'unarchive': name + ' is editable again.'}[action]
    if action == 'release-lock':
        repo, path = form.get('repo', ''), form.get('path', '')
        if repo not in repositories() or not any(l['path'] == path for l in locks(repo)):
            raise Refused('That lock no longer exists.')
        # rmlocks bypasses the student pre-unlock hook; unsubmitted edits on the owner's PC become stale.
        run('svnadmin', 'rmlocks', os.path.join(REPOS, repo), path)
        return 'Released ' + path + '. The previous owner can no longer submit their unsaved copy of it.'
    if action in ('add-user', 'reset-password'):
        name = form.get('username', '').strip().lower()
        password = form.get('password', '')
        if not USERNAME.match(name):
            raise Refused('Usernames: 2–32 lowercase letters, numbers, dot, dash, underscore.')
        if len(password) < 10:
            raise Refused('Passwords must be at least 10 characters.')
        if (action == 'add-user') == (name in users()):
            raise Refused(name + (' already exists.' if action == 'add-user' else ' does not exist.'))
        run('htpasswd', '-B', '-i', USERS, name, stdin=password.encode())
        if action == 'add-user' and form.get('mentor'):
            state['mentors'] = sorted(set(state['mentors']) | {name})
            save_state(state)
        return ('Added ' if action == 'add-user' else 'Reset password for ') + name + '.'
    if action in ('delete-user', 'toggle-mentor'):
        name = form.get('username', '')
        if name not in users():
            raise Refused('Unknown user.')
        if name == user:
            raise Refused('You cannot remove your own account or mentor role.')
        if name == PUBLISHER and action == 'toggle-mentor':
            raise Refused(PUBLISHER + ' is the GitHub release uploader and cannot be a mentor.')
        if action == 'delete-user':
            held = [l for r in repositories() for l in locks(r) if l.get('owner') == name]
            if held:
                raise Refused(name + ' still holds ' + str(len(held)) + ' lock(s). Release them first.')
            run('htpasswd', '-D', USERS, name)
            state['mentors'] = [m for m in state['mentors'] if m != name]
            save_state(state)
            return 'Deleted ' + name + '. Their history is kept.'
        state['mentors'] = sorted(set(state['mentors']) ^ {name})
        save_state(state)
        return name + (' is now a mentor.' if name in state['mentors'] else ' is no longer a mentor.')
    if action in ('release-staged', 'discard-staged'):
        staged = state.get('staged_addin')
        if not staged:
            raise Refused('Nothing is staged.')
        path = os.path.join(UPDATES, 'staged', staged['file'])
        if action == 'discard-staged':
            shutil.rmtree(os.path.join(UPDATES, 'staged'), ignore_errors=True)
            state.pop('staged_addin', None)
            save_state(state)
            return 'Discarded staged ' + staged['version'] + '.'
        with open(path, 'rb') as handle:
            data = handle.read()
        if hashlib.sha256(data).hexdigest() != staged['sha256']:
            raise Refused('The staged file changed on the server. Discard it and re-run the GitHub release.')
        return release_addin(staged['file'], data, form.get('required'))
    if action == 'addin-required':
        if not state.get('addin'):
            raise Refused('No add-in has been published yet.')
        state['addin']['required'] = not state['addin'].get('required')
        save_state(state)
        return 'Add-in %s is now %s.' % (state['addin']['version'], 'required' if state['addin']['required'] else 'optional')
    if action == 'promote':
        repo, _, source = form.get('choice', '').partition('|')
        if repo not in repositories() or not SEASON.match(repo) or source not in files(repo):
            raise Refused('Choose a CAD file from a season.')
        target = clean_path(form.get('folder', '') + '/' + source.rsplit('/', 1)[-1])
        with tempfile.NamedTemporaryFile() as temp:
            temp.write(subprocess.run(['svnlook', 'cat', os.path.join(REPOS, repo), source], capture_output=True, check=True).stdout)
            temp.flush()
            add_to_library([(target, temp.name)], user, 'Add %s from %s:/%s' % (target, repo, source))
        return 'Added ' + target + ' to the library.'
    raise Refused('Unknown action.')


def version_key(text):
    return tuple(int(x) for x in text.split('.'))


def check_installer(name, data, expected_sha=None):
    """Returns (version, sha256) for an installer that is safe to offer, or raises Refused."""
    match = INSTALLER.match(name)
    if not match:
        raise Refused('Use the file made by Build-Installer.ps1 or GitHub, named like JOCO-ROBOS-CAD-Setup-0.6.0.exe.')
    if not data.startswith(b'MZ'):
        raise Refused(name + ' is not a Windows program.')
    digest = hashlib.sha256(data).hexdigest()
    if expected_sha and digest != expected_sha.strip().lower():
        raise Refused('%s does not match the expected SHA-256 (got %s, %.1f MB). The download was probably incomplete; download it again.'
                      % (name, digest, len(data) / 1048576.0))
    version = '.'.join(match.groups())
    current = load_state().get('addin')
    if current and version_key(version) <= version_key(current['version']):
        raise Refused('Version %s is not newer than the published %s. Bump <Version> in the .csproj and rebuild.' % (version, current['version']))
    return version, digest


def store(folder, name, data):
    os.makedirs(folder, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=folder, delete=False) as handle:
        handle.write(data)
    os.chmod(handle.name, 0o644)
    os.replace(handle.name, os.path.join(folder, name))


def release_addin(name, data, required):
    version, digest = check_installer(name, data)
    store(UPDATES, name, data)
    state = load_state()
    state['addin'] = {'version': version, 'file': name, 'sha256': digest, 'required': bool(required), 'size': len(data)}
    state.pop('staged_addin', None)
    save_state(state)
    # Keep the three newest installers so students mid-download are not cut off.
    old = sorted((f for f in os.listdir(UPDATES) if INSTALLER.match(f)), key=lambda f: version_key('.'.join(INSTALLER.match(f).groups())))
    for stale in old[:-3]:
        os.remove(os.path.join(UPDATES, stale))
    shutil.rmtree(os.path.join(UPDATES, 'staged'), ignore_errors=True)
    return 'Published add-in %s%s. Students are offered it the next time SOLIDWORKS checks.' % (version, ' as a required update' if required else '')


def stage_addin(name, data, expected_sha):
    """Called by GitHub Actions: holds a verified installer until a mentor releases it."""
    if not expected_sha:
        raise Refused('Missing SHA-256.')
    version, digest = check_installer(name, data, expected_sha)
    shutil.rmtree(os.path.join(UPDATES, 'staged'), ignore_errors=True)
    os.makedirs(os.path.join(UPDATES, 'staged'), mode=0o700)
    store(os.path.join(UPDATES, 'staged'), name, data)
    state = load_state()
    state['staged_addin'] = {'version': version, 'file': name, 'sha256': digest, 'size': len(data), 'at': time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}
    save_state(state)
    return 'Staged %s for mentor release.' % version


def publish_addin(fields):
    uploads = fields.get('files', [])
    if len(uploads) != 1:
        raise Refused('Choose one JOCO-ROBOS-CAD-Setup-x.y.z.exe file.')
    name, data = os.path.basename(uploads[0][0].replace('\\', '/')), uploads[0][1]
    check_installer(name, data, fields.get('sha256', b'').decode('ascii', 'replace') or None)
    return release_addin(name, data, fields.get('required'))


def upload(user, fields):
    if fields.get('kind') == b'addin':
        return publish_addin(fields)
    folder = clean_path(fields.get('folder', b'').decode('utf-8', 'replace') or 'Hardware')
    message = fields.get('comment', b'').decode('utf-8', 'replace').strip() or 'Add parts to library'
    uploads = [(clean_path(folder + '/' + os.path.basename(name.replace('\\', '/'))), data) for name, data in fields.get('files', [])]
    if not uploads:
        raise Refused('Choose one or more SOLIDWORKS files.')
    with tempfile.TemporaryDirectory() as scratch:
        entries = []
        for i, (target, data) in enumerate(uploads):
            local = os.path.join(scratch, str(i))
            with open(local, 'wb') as handle:
                handle.write(data)
            entries.append((target, local))
        add_to_library(entries, user, message)
    return 'Added %d file(s) to the library.' % len(uploads)


# ---------- web page ----------

STYLE = '''
:root{--bg:#f6f7f9;--card:#fff;--ink:#16181d;--muted:#5d6470;--line:#dde1e7;--accent:#1f5fbf;--ok:#1d7a46;--warn:#9a5b00;--bad:#b3261e}
@media (prefers-color-scheme:dark){:root{--bg:#121417;--card:#1b1e23;--ink:#e8eaee;--muted:#9aa2ad;--line:#2c3139;--accent:#79a8f0;--ok:#5cc28a;--warn:#e0a84a;--bad:#f08079}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}
header{display:flex;gap:20px;align-items:center;flex-wrap:wrap;padding:14px 20px;border-bottom:1px solid var(--line);background:var(--card)}
header b{font-size:17px}nav a{margin-right:14px;color:var(--muted);text-decoration:none}nav a.on{color:var(--ink);font-weight:600}
main{max-width:1050px;margin:0 auto;padding:20px 16px}section{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin-bottom:18px}
h2{font-size:16px;margin:0 0 12px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:7px 8px;border-top:1px solid var(--line);vertical-align:top}
th{color:var(--muted);font-weight:500;font-size:13px;border-top:0}.muted{color:var(--muted)}.tag{font-size:12px;padding:1px 7px;border-radius:9px;border:1px solid var(--line)}
.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}form.inline{display:inline}
input,select,button{font:inherit;padding:6px 9px;border:1px solid var(--line);border-radius:6px;background:var(--bg);color:var(--ink)}
button{cursor:pointer;background:var(--card)}button.primary{background:var(--accent);border-color:var(--accent);color:#fff}
.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:8px}.notice{padding:10px 14px;border-radius:8px;margin-bottom:16px;border:1px solid var(--line);background:var(--card)}
code{font-size:13px}.scroll{overflow-x:auto}
'''


def esc(value):
    return html.escape(str(value), quote=True)


class Admin(BaseHTTPRequestHandler):
    server_version = 'JocoAdmin'

    def log_message(self, fmt, *args):
        sys.stderr.write('admin: %s %s\n' % (self.headers.get('X-Joco-User', '-'), fmt % args))

    @property
    def user(self):
        return self.headers.get('X-Joco-User', '')

    def token(self):
        with open(SECRET) as handle:
            return hmac.new(handle.read().encode(), self.user.encode(), hashlib.sha256).hexdigest()

    def guard(self):
        state = load_state()
        if not self.user or self.user not in state['mentors']:
            self.page('Mentors only', '<section><h2>Mentors only</h2><p>This page is for mentors. Students do everything from SOLIDWORKS.</p></section>', '', status=403)
            return None
        return state

    def do_GET(self):
        state = self.guard()
        if state is None:
            return
        path = urlsplit(self.path).path.rstrip('/')
        query = parse_qs(urlsplit(self.path).query)
        notice = query.get('ok', [''])[0]
        error = query.get('error', [''])[0]
        pages = {'/admin': self.home, '/admin/locks': self.locks_page, '/admin/library': self.library_page, '/admin/users': self.users_page, '/admin/addin': self.addin_page}
        if path not in pages:
            self.send_error(404)
            return
        try:
            body = pages[path](state)
        except Refused as exc:
            body, error = '', str(exc)
        banner = ''
        if notice:
            banner = '<div class="notice ok">' + esc(notice) + '</div>'
        if error:
            banner = '<div class="notice bad">' + esc(error) + '</div>'
        self.page({'/admin': 'Seasons', '/admin/locks': 'Locks', '/admin/library': 'Library', '/admin/users': 'Accounts', '/admin/addin': 'Add-in'}[path], banner + body, path)

    def do_POST(self):
        if urlsplit(self.path).path == '/admin/api/stage-addin':
            return self.stage()
        state = self.guard()
        if state is None:
            return
        back = urlsplit(self.path).path.rstrip('/') or '/admin'
        if back not in ('/admin', '/admin/locks', '/admin/library', '/admin/users', '/admin/addin'):
            back = '/admin'
        try:
            # Browsers resend Basic credentials automatically: require same-origin plus a per-user token.
            origin = self.headers.get('Origin') or self.headers.get('Referer') or ''
            host = self.headers.get('X-Forwarded-Host', self.headers.get('Host', '')).split(',')[0].strip()
            if urlsplit(origin).netloc != host:
                raise Refused('Request blocked: it did not come from this page.')
            length = int(self.headers.get('Content-Length', '0'))
            if length > MAX_UPLOAD + 65536:
                raise Refused('Upload is larger than 100 MB. Add big assemblies from SOLIDWORKS with Submit instead.')
            raw = self.rfile.read(length)
            kind = self.headers.get('Content-Type', '')
            if kind.startswith('multipart/form-data'):
                fields = self.multipart(kind, raw)
                if not hmac.compare_digest(fields.get('token', b'').decode(), self.token()):
                    raise Refused('Your page expired. Reload and try again.')
                with Locked():
                    message = upload(self.user, fields)
            else:
                form = {k: v[0] for k, v in parse_qs(raw.decode('utf-8'), keep_blank_values=True).items()}
                if not hmac.compare_digest(form.get('token', ''), self.token()):
                    raise Refused('Your page expired. Reload and try again.')
                with Locked():
                    message = act(self.user, form)
            self.redirect(back + '?ok=' + quote(message))
        except Refused as exc:
            self.redirect(back + '?error=' + quote(str(exc)[:600]))

    def stage(self):
        # Only the GitHub release account; it has no mentor page and no SVN access.
        if self.user != PUBLISHER:
            return self.reply(403, 'Only the GitHub release account can stage installers.')
        try:
            length = int(self.headers.get('Content-Length', '0'))
            if length > MAX_UPLOAD:
                raise Refused('Installer is larger than 100 MB.')
            data = self.rfile.read(length)
            with Locked():
                message = stage_addin(os.path.basename(self.headers.get('X-Joco-File', '')), data, self.headers.get('X-Joco-Sha256', ''))
            self.reply(200, message)
        except Refused as exc:
            self.reply(400, str(exc))

    def reply(self, status, text):
        data = (text + '\n').encode()
        self.send_response(status)
        self.send_header('Content-Type', 'text/plain; charset=utf-8')
        self.send_header('Content-Length', str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    @staticmethod
    def multipart(kind, raw):
        message = BytesParser(policy=HTTP).parsebytes(b'Content-Type: ' + kind.encode() + b'\r\n\r\n' + raw)
        fields = {'files': []}
        for part in message.iter_parts():
            name = part.get_param('name', header='content-disposition')
            if part.get_filename():
                if part.get_filename().strip():
                    fields['files'].append((part.get_filename(), part.get_payload(decode=True)))
            elif name:
                fields[name] = part.get_payload(decode=True) or b''
        return fields

    def redirect(self, location):
        self.send_response(303)
        self.send_header('Location', location)
        self.send_header('Content-Length', '0')
        self.end_headers()

    def page(self, title, body, current, status=200):
        links = [('/admin', 'Seasons'), ('/admin/locks', 'Locks'), ('/admin/library', 'Library'), ('/admin/users', 'Accounts'), ('/admin/addin', 'Add-in')]
        nav = ''.join('<a href="%s"%s>%s</a>' % (h, ' class="on"' if h == current else '', t) for h, t in links)
        text = ('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
                '<title>%s · JOCO ROBOS CAD</title><style>%s</style></head><body><header><b>JOCO ROBOS CAD</b><nav>%s</nav>'
                '<span class="muted">%s</span></header><main>%s</main></body></html>') % (esc(title), STYLE, nav, esc(self.user), body)
        data = text.encode()
        self.send_response(status)
        self.send_header('Content-Type', 'text/html; charset=utf-8')
        self.send_header('Content-Length', str(len(data)))
        self.send_header('Cache-Control', 'no-store')
        self.send_header('X-Frame-Options', 'DENY')
        self.send_header('Content-Security-Policy', "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'")
        self.end_headers()
        self.wfile.write(data)

    def form(self, action, fields, label, extra='', primary=False, confirm=None):
        hidden = ''.join('<input type="hidden" name="%s" value="%s">' % (esc(k), esc(v)) for k, v in fields.items())
        return ('<form class="inline" method="post"><input type="hidden" name="token" value="%s"><input type="hidden" name="action" value="%s">%s%s'
                '<button%s>%s</button></form>') % (self.token(), esc(action), hidden, extra, ' class="primary"' if primary else '', esc(label))

    def home(self, state):
        seasons = [n for n in repositories() if SEASON.match(n)]
        rows = ''
        for name in reversed(seasons):
            held = locks(name)
            if name == state['active']:
                status, actions = '<span class="ok">● Active — students open this</span>', ''
            elif name in state['archived']:
                status, actions = '<span class="muted">Archived (read-only)</span>', self.form('unarchive', {'name': name}, 'Unarchive')
            else:
                status = '<span class="warn">Editable, not active</span>'
                actions = self.form('activate', {'name': name}, 'Make active') + ' ' + self.form('archive', {'name': name}, 'Archive')
                if youngest(name) <= 1 and not held:
                    actions += ' ' + self.form('delete-season', {'name': name}, 'Delete (empty)')
            rows += '<tr><td><b>%s</b></td><td>r%d</td><td>%d</td><td>%s</td><td>%s</td></tr>' % (esc(name), youngest(name), len(held), status, actions)
        next_year = (int(seasons[-1][:4]) + 1) if seasons else 2027
        create = ('<form method="post" class="row"><input type="hidden" name="token" value="%s"><input type="hidden" name="action" value="create-season">'
                  '<input name="name" value="%d-Robot" pattern="(19|20)[0-9]{2}-Robot" required aria-label="Season name">'
                  '<label><input type="checkbox" name="activate" value="1"> Make it active now</label><button class="primary">Create season</button></form>'
                  '<p class="muted">Creates the standard subsystem folders with lock rules and daily backups. Students switch automatically the next time they click Open Robot or Update. '
                  'Reuse parts by adding them to the Library; students insert them with “Insert from Library”.</p>') % (self.token(), next_year)
        recent = activity(seasons[-2:] + [LIBRARY])
        log = ''.join('<tr><td>%s</td><td class="muted">%s r%d</td><td>%s</td><td>%s<div class="muted">%s</div></td></tr>' % (
            esc(e['date']), esc(e['repo']), e['rev'], esc(e['author']), esc(e['msg']),
            esc(', '.join(f.rsplit('/', 1)[-1] for f in e['files'][:6]) + (' …' if len(e['files']) > 6 else ''))) for e in recent)
        return ('<section><h2>Robot seasons</h2><div class="scroll"><table><tr><th>Season</th><th>Revision</th><th>Locks</th><th>Status</th><th></th></tr>%s</table></div></section>'
                '<section><h2>Start a new season</h2>%s</section>'
                '<section><h2>Recent submits</h2><div class="scroll"><table><tr><th>When (UTC)</th><th>Where</th><th>Who</th><th>What</th></tr>%s</table></div></section>') % (
                    rows or '<tr><td colspan="5" class="muted">No seasons yet.</td></tr>', create, log or '<tr><td colspan="4" class="muted">Nothing yet.</td></tr>')

    def locks_page(self, state):
        rows = ''
        for name in repositories():
            for lock in locks(name):
                rows += '<tr><td>%s</td><td><code>%s</code></td><td><b>%s</b></td><td class="muted">%s</td><td>%s</td></tr>' % (
                    esc(name), esc(lock['path']), esc(lock.get('owner', '?')), esc(lock.get('created', '')),
                    self.form('release-lock', {'repo': name, 'path': lock['path']}, 'Release'))
        return ('<section><h2>Locked files</h2><p class="muted">Release a lock only when its owner cannot Submit (lost laptop, left the team). '
                'Any unsubmitted changes on their computer can then no longer be submitted.</p><div class="scroll"><table>'
                '<tr><th>Where</th><th>File</th><th>Locked by</th><th>Since</th><th></th></tr>%s</table></div></section>') % (
                    rows or '<tr><td colspan="5" class="muted">Nothing is locked.</td></tr>')

    def addin_page(self, state):
        current = state.get('addin')
        if current:
            info = ('<p>Published: <b>%s</b> (%s, %.1f MB) — %s</p><p class="muted">SHA-256 <code>%s</code></p>%s') % (
                esc(current['version']), esc(current['file']), current.get('size', 0) / 1048576.0,
                '<span class="bad">required: students must install it before Edit or Submit</span>' if current.get('required')
                else '<span class="ok">optional: students are offered it</span>', esc(current['sha256']),
                self.form('addin-required', {}, 'Make optional' if current.get('required') else 'Make required'))
        else:
            info = '<p class="muted">Nothing published yet. Students keep whatever version they installed.</p>'
        staged = state.get('staged_addin')
        if staged:
            staged_html = ('<p><b>%s</b> from GitHub, staged %s (%.1f MB, SHA-256 verified <code>%s…</code>)</p><div class="row">%s %s %s</div>') % (
                esc(staged['version']), esc(staged.get('at', '')), staged['size'] / 1048576.0, esc(staged['sha256'][:16]),
                self.form('release-staged', {}, 'Release to students', primary=True),
                self.form('release-staged', {'required': '1'}, 'Release as required'),
                self.form('discard-staged', {}, 'Discard'))
        else:
            staged_html = '<p class="muted">Nothing waiting. Push a version tag (for example <code>v0.6.3</code>) and GitHub stages the installer here.</p>'
        upload_form = ('<form method="post" enctype="multipart/form-data" class="row"><input type="hidden" name="token" value="%s">'
                       '<input type="hidden" name="kind" value="addin"><input type="file" name="files" accept=".exe" required>'
                       '<input name="sha256" placeholder="SHA-256 from the GitHub release (recommended)" size="40" pattern="[0-9a-fA-F]{64}" aria-label="Expected SHA-256">'
                       '<label><input type="checkbox" name="required" value="1"> Required</label><button class="primary">Publish</button></form>'
                       '<p class="muted">On the Windows PC: bump <code>&lt;Version&gt;</code> in <code>JocoRobos.Cad.csproj</code>, run '
                       '<code>scripts\\Build-Installer.ps1</code>, and upload <code>installer\\Output\\JOCO-ROBOS-CAD-Setup-x.y.z.exe</code>. '
                       'Students get a prompt in SOLIDWORKS; after they save and close SOLIDWORKS it installs and reopens. '
                       'Use <b>Required</b> when the server or file format changed and older add-ins must not submit.</p>') % self.token()
        return ('<section><h2>Student add-in</h2>%s</section><section><h2>Waiting from GitHub</h2>%s</section>'
                '<section><h2>Upload manually</h2>%s</section>') % (info, staged_html, upload_form)

    def library_page(self, state):
        parts = files(LIBRARY) if LIBRARY in repositories() else []
        held = {l['path'].lstrip('/'): l.get('owner') for l in (locks(LIBRARY) if LIBRARY in repositories() else [])}
        rows, folder = '', None
        for path in parts:
            parent, _, name = path.rpartition('/')
            if parent != folder:
                folder = parent
                rows += '<tr><td colspan="2"><b>%s</b></td></tr>' % esc(parent or '(top level)')
            rows += '<tr><td>&nbsp;&nbsp;%s</td><td class="muted">%s</td></tr>' % (esc(name), ('🔒 ' + esc(held[path])) if path in held else '')
        folders = sorted({p.rpartition('/')[0] for p in parts if '/' in p} | set(LIBRARY_FOLDERS))
        options = ''.join('<option>%s</option>' % esc(f) for f in folders)
        seasons = [n for n in repositories() if SEASON.match(n)]
        sources = ''.join('<option value="%s|%s">%s — %s</option>' % (esc(s), esc(f), esc(s), esc(f)) for s in reversed(seasons) for f in files(s))
        token = self.token()
        return ('<section><h2>Reusable parts library</h2><p class="muted">Every student has a copy at <code>C:\\JOCO-ROBOS\\Library</code>. '
                '“Insert from Library” copies a part into the robot the first time it is used there. That copy then belongs to the robot: '
                'later library changes never replace it, so mates and geometry can\'t change underneath a design. '
                'Students can also improve library parts with Edit and Submit.</p><div class="scroll"><table><tr><th>Part</th><th></th></tr>%s</table></div></section>'
                '<section><h2>Upload new parts</h2><form method="post" enctype="multipart/form-data" class="row"><input type="hidden" name="token" value="%s">'
                '<input type="file" name="files" multiple accept=".sldprt,.sldasm,.slddrw" required>'
                '<input name="folder" list="folders" value="Hardware" required aria-label="Library folder"><datalist id="folders">%s</datalist>'
                '<input name="comment" placeholder="Comment (optional)" aria-label="Comment"><button class="primary">Upload</button></form>'
                '<p class="muted">Up to 100 MB. For an assembly, upload it together with all of its parts in one go. New folder names are fine.</p></section>'
                '<section><h2>Copy a robot part into the library</h2><form method="post" class="row"><input type="hidden" name="token" value="%s">'
                '<input type="hidden" name="action" value="promote"><select name="choice" required aria-label="Robot file">%s</select>'
                '<input name="folder" list="folders" value="Mechanisms" required aria-label="Library folder"><button class="primary">Add to library</button></form></section>') % (
                    rows or '<tr><td colspan="2" class="muted">Empty so far.</td></tr>', token, options, token, sources or '<option value="">No robot files yet</option>')

    def users_page(self, state):
        rows = ''
        for name in users():
            mentor = name in state['mentors']
            reset = self.form('reset-password', {'username': name}, 'Reset password',
                              '<input type="password" name="password" minlength="10" placeholder="New password" required autocomplete="new-password" aria-label="New password for %s"> ' % esc(name))
            tools = '' if name == self.user else (self.form('toggle-mentor', {'username': name}, 'Remove mentor' if mentor else 'Make mentor') + ' ' +
                                                   self.form('delete-user', {'username': name}, 'Delete'))
            rows += '<tr><td><b>%s</b> %s</td><td>%s</td><td>%s</td></tr>' % (esc(name), '<span class="tag">mentor</span>' if mentor else '', reset, tools)
        add = ('<form method="post" class="row"><input type="hidden" name="token" value="%s"><input type="hidden" name="action" value="add-user">'
               '<input name="username" placeholder="username (e.g. sarah)" pattern="[a-z0-9][a-z0-9._\\-]{1,31}" required aria-label="Username">'
               '<input type="password" name="password" minlength="10" placeholder="Starting password" required autocomplete="new-password" aria-label="Starting password">'
               '<label><input type="checkbox" name="mentor" value="1"> Mentor</label><button class="primary">Add account</button></form>'
               '<p class="muted">Give the student their username and password privately. They sign in once from SOLIDWORKS; it is saved in Windows.</p>') % self.token()
        return ('<section><h2>Add an account</h2>%s</section><section><h2>Accounts</h2><div class="scroll"><table>'
                '<tr><th>User</th><th>Password</th><th></th></tr>%s</table></div></section>') % (add, rows)


def serve():
    server = ThreadingHTTPServer(('127.0.0.1', int(os.environ.get('JOCO_ADMIN_PORT', '8092'))), Admin)
    server.serve_forever()


if __name__ == '__main__':
    command = sys.argv[1:2] or ['']
    if command == ['ensure']:
        ensure()
    elif command == ['serve']:
        serve()
    elif command == ['mentor'] and len(sys.argv) == 4 and sys.argv[2] in ('add', 'remove'):
        with Locked():
            state = load_state()
            if sys.argv[3] not in users():
                sys.exit('Unknown user: ' + sys.argv[3])
            state['mentors'] = sorted((set(state['mentors']) | {sys.argv[3]}) if sys.argv[2] == 'add' else (set(state['mentors']) - {sys.argv[3]}))
            save_state(state)
        print('Mentors: ' + ', '.join(state['mentors']))
    else:
        sys.exit('usage: joco.py ensure | serve | mentor add|remove USER')
