#!/usr/bin/python3
"""JOCO ROBOS CAD server administration: seasons, library, locks, and accounts.

`joco.py ensure` runs at container start. `joco.py serve` is the mentor web page,
listening only inside the container; Apache authenticates users and forwards
/admin with the verified username. Students never need this page.
"""
import calendar
import fcntl
import hashlib
import hmac
import html
import json
import os
import re
import secrets
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import xml.etree.ElementTree as ElementTree
from email.parser import BytesParser
from email.policy import HTTP
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, quote, urlsplit

import frcdesign

REPOS = os.environ.get('JOCO_REPOS', '/var/lib/svn')
CONFIG = os.environ.get('JOCO_CONFIG', '/etc/joco')
HOOKS = os.environ.get('JOCO_HOOKS', '/opt/joco')
USERS = os.path.join(CONFIG, 'users')
STATE = os.path.join(CONFIG, 'state.json')
AUTHZ = os.path.join(CONFIG, 'authz')
CATALOG = os.path.join(CONFIG, 'public', 'catalog.json')
SECRET = os.path.join(CONFIG, 'admin-secret')
UPDATES = os.path.join(CONFIG, 'public', 'updates')
HEALTH = os.path.join(CONFIG, 'health')
HEARTBEATS = os.path.join(CONFIG, 'heartbeats.json')
INVITES = os.path.join(CONFIG, 'invites.json')
REQUESTS = os.path.join(CONFIG, 'requests.json')  # Students asking for an account, waiting for a mentor's code.
MAX_REQUESTS = 40
CODE_ALPHABET = 'ABCDEFGHJKMNPQRSTUVWXYZ23456789'  # No 0/O, 1/I/L.
INVITE_DAYS = 7
_setup_attempts = {}  # address -> [times]; in memory, reset on restart.
INSTALLER = re.compile(r'^JOCO-ROBOS-CAD-Setup-(\d{1,4})\.(\d{1,4})\.(\d{1,4})\.exe$')
LIBRARY = 'Library'
# GitHub Actions account: may only stage installers, never touch CAD or the admin pages.
PUBLISHER = 'github-release'
SEASON = re.compile(r'^(19|20)\d{2}-Robot$')
USERNAME = re.compile(r'^[a-z0-9][a-z0-9._-]{1,31}$')
SEGMENT = re.compile(r'^[A-Za-z0-9][A-Za-z0-9 _().&+,-]{0,99}$')
CAD = ('.sldprt', '.sldasm', '.slddrw')
ROBOT_FOLDERS = ['00_Master', '10_Drivetrain', '20_Intake', '30_Shooter', '40_Climber', '50_Electrical', '90_COTS']
LIBRARY_FOLDERS = ['Motors', 'Gearboxes', 'Wheels', 'Electronics', 'Hardware', 'Mechanisms']
MAX_UPLOAD = 100 * 1024 * 1024  # Cloudflare's request limit on the free plan.
_mutex = threading.Lock()


class Refused(Exception):
    """A request that was understood but not allowed; shown to the mentor."""


def run(*args, stdin=None):
    result = subprocess.run(args, input=stdin, capture_output=True)
    if result.returncode != 0:
        raise Refused((result.stderr or result.stdout).decode('utf-8', 'replace').strip() or 'Command failed: ' + args[0])
    return result.stdout.decode('utf-8', 'replace')


class Locked:
    """Serialize changes across web threads and `podman exec` maintenance."""
    def __enter__(self):
        _mutex.acquire()
        self.handle = open(os.path.join(CONFIG, '.admin.lock'), 'w')
        fcntl.flock(self.handle, fcntl.LOCK_EX)

    def __exit__(self, *_):
        fcntl.flock(self.handle, fcntl.LOCK_UN)
        self.handle.close()
        _mutex.release()


def write_atomic(path, text, mode=0o640):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, temp = tempfile.mkstemp(dir=os.path.dirname(path))
    with os.fdopen(fd, 'w') as handle:
        handle.write(text)
    os.chmod(temp, mode)
    os.replace(temp, path)


# ---------- state ----------

def repositories():
    # Dot-folders hold deleted seasons; they are not served or backed up.
    return sorted(n for n in os.listdir(REPOS) if not n.startswith('.') and os.path.isfile(os.path.join(REPOS, n, 'format')))


def load_state():
    try:
        with open(STATE) as handle:
            state = json.load(handle)
    except FileNotFoundError:
        seasons = [n for n in repositories() if SEASON.match(n)]
        state = {'active': seasons[-1] if seasons else None, 'archived': [], 'mentors': []}
    state.setdefault('archived', [])
    state.setdefault('mentors', [])
    return state


def save_state(state):
    write_atomic(STATE, json.dumps(state, indent=2) + '\n')
    publish(state)


def uuid(name):
    return run('svnlook', 'uuid', os.path.join(REPOS, name)).strip()


def publish(state):
    """Regenerate SVN access rules and the catalog the add-in reads."""
    # "~name" = every signed-in account except the release uploader.
    rules = ['# Generated by joco.py from state.json; edit through the admin page.', '[/]', '~%s = rw' % PUBLISHER, '']
    for name in state['archived']:
        rules += ['[%s:/]' % name, '~%s = r' % PUBLISHER, '']
    write_atomic(AUTHZ, '\n'.join(rules))
    seasons = [n for n in repositories() if SEASON.match(n)]
    catalog = {
        'version': 1,
        'active': state['active'],
        'robots': [{'name': n, 'uuid': uuid(n), 'archived': n in state['archived'], 'master': state.get('masters', {}).get(n)} for n in seasons],
        'library': {'name': LIBRARY, 'uuid': uuid(LIBRARY)} if LIBRARY in repositories() else None,
        # Newest published student installer; the add-in offers it when it is newer than itself.
        'addin': state.get('addin'),
        # The team's SOLIDWORKS version (a year). A newer SOLIDWORKS would save files older ones can't open, so the add-in
        # won't edit or submit team CAD from it.
        'solidworks': state.get('solidworks'),
    }
    write_atomic(CATALOG, json.dumps(catalog, indent=2) + '\n', 0o644)


def install_hooks(name):
    hooks = os.path.join(REPOS, name, 'hooks')
    for hook in ('pre-commit', 'pre-lock', 'pre-unlock'):
        shutil.copyfile(os.path.join(HOOKS, hook), os.path.join(hooks, hook))
        os.chmod(os.path.join(hooks, hook), 0o755)


def create_repository(name, folders, author, message):
    path = os.path.join(REPOS, name)
    if os.path.exists(path):
        raise Refused(name + ' already exists.')
    run('svnadmin', 'create', path)
    install_hooks(name)
    if not folders:
        return
    args = ['svnmucc', '--non-interactive', '--username', author, '-m', message, '-U', 'file://' + path]
    for folder in folders:
        args += ['mkdir', folder]
    run(*args)


def create_test_season(name, source):
    """A full copy of a season (files and history, no locks) for release testing; removable afterwards."""
    if not SEASON.match(name) or name in repositories():
        raise Refused(name + ' must be a new name like 2099-Robot.')
    if source not in repositories() or not SEASON.match(source):
        raise Refused('Unknown season ' + source + '.')
    path = os.path.join(REPOS, name)
    run('svnadmin', 'hotcopy', os.path.join(REPOS, source), path)
    run('svnadmin', 'setuuid', path)  # Its own identity: add-ins never mistake it for the real season.
    for lock in locks(name):
        run('svnadmin', 'rmlocks', path, lock['path'])
    install_hooks(name)
    state = load_state()
    state.setdefault('test_seasons', []).append(name)
    if source in state.get('masters', {}):
        state['masters'][name] = state['masters'][source]
    save_state(state)
    return youngest(name)


def remove_test_season(name):
    state = load_state()
    if name not in state.get('test_seasons', []):
        raise Refused(name + ' is not a test season, so it is never removed this way.')
    if name == state['active']:
        raise Refused('Make another season active first.')
    stamp = time.strftime('%Y%m%dT%H%M%SZ', time.gmtime())
    os.rename(os.path.join(REPOS, name), os.path.join(REPOS, '.deleted-%s-%s' % (name, stamp)))
    state['test_seasons'].remove(name)
    state.get('masters', {}).pop(name, None)
    state['archived'] = [n for n in state['archived'] if n != name]
    save_state(state)


def has_files(name):
    """True once a season holds any file. Only file-less seasons may be deleted."""
    return any(line and not line.endswith('/') for line in run('svnlook', 'tree', '--full-paths', os.path.join(REPOS, name)).splitlines())


CAD_PATTERNS = ('[Ss][Ll][Dd][Pp][Rr][Tt]', '[Ss][Ll][Dd][Aa][Ss][Mm]', '[Ss][Ll][Dd][Dd][Rr][Ww]')


def import_season(name, directory, author, message):
    """Creates a season from an existing folder tree exactly as it is, with lock properties on every CAD file."""
    if not SEASON.match(name):
        raise Refused('Season names look like 2026-Robot.')
    if not os.path.isdir(directory) or not any(files for _, _, files in os.walk(directory)):
        raise Refused('Nothing to import in ' + directory)
    create_repository(name, [], author, message)
    options = ['--config-option', 'config:miscellany:enable-auto-props=yes', '--config-option', 'config:miscellany:global-ignores=']
    for pattern in CAD_PATTERNS:
        options += ['--config-option', 'config:auto-props:*.%s=svn:needs-lock=*;svn:mime-type=application/octet-stream' % pattern]
    run('svn', 'import', '--non-interactive', '--no-auth-cache', '--username', author, '-m', message, *options,
        directory, 'file://' + os.path.join(REPOS, name))
    return verify_import(name, directory)


def verify_import(name, directory):
    """Every file byte-identical in the repository, and every CAD file carries the lock properties."""
    repo = os.path.join(REPOS, name)
    count = 0
    for root, _, names in os.walk(directory):
        for filename in names:
            local = os.path.join(root, filename)
            relative = os.path.relpath(local, directory).replace(os.sep, '/')
            stored = subprocess.run(['svnlook', 'cat', repo, relative], capture_output=True)
            with open(local, 'rb') as handle:
                if stored.returncode != 0 or stored.stdout != handle.read():
                    raise Refused('Imported copy of %s does not match. The season was left in place for inspection.' % relative)
            if relative.lower().endswith(CAD):
                if run('svnlook', 'propget', repo, 'svn:needs-lock', relative).strip() != '*':
                    raise Refused('%s is missing its lock property.' % relative)
            count += 1
    return count


def ensure():
    """Container start: hooks everywhere, a Library repository, consistent generated files."""
    with Locked():
        if LIBRARY not in repositories():
            create_repository(LIBRARY, LIBRARY_FOLDERS, 'joco-admin', 'Create reusable parts library')
        for name in repositories():
            install_hooks(name)
        if not os.path.exists(SECRET):
            write_atomic(SECRET, secrets.token_hex(32), 0o600)
        state = load_state()
        state['archived'] = [n for n in state['archived'] if n in repositories()]
        save_state(state)


# ---------- repository queries ----------

def youngest(name):
    return int(run('svnlook', 'youngest', os.path.join(REPOS, name)))


def locks(name):
    result, current = [], None
    for line in run('svnadmin', 'lslocks', os.path.join(REPOS, name)).splitlines():
        if line.startswith('Path: '):
            current = {'repo': name, 'path': line[6:]}
            result.append(current)
        elif current and line.startswith('Owner: '):
            current['owner'] = line[7:]
        elif current and line.startswith('Created: '):
            current['created'] = line[9:].split(' (')[0]
    return result


def activity(names, limit=15):
    entries = []
    for name in names:
        root = ElementTree.fromstring(run('svn', 'log', '--xml', '-v', '-l', str(limit), 'file://' + os.path.join(REPOS, name)))
        for entry in root.findall('logentry'):
            entries.append({
                'repo': name, 'rev': int(entry.get('revision')),
                'author': entry.findtext('author') or '', 'date': (entry.findtext('date') or '')[:16].replace('T', ' '),
                'msg': (entry.findtext('msg') or '').strip(),
                'files': [p.text for p in entry.findall('paths/path') if p.get('kind') == 'file'],
            })
    return sorted(entries, key=lambda e: e['date'], reverse=True)[:limit]


def files(name):
    listing = run('svnlook', 'tree', '--full-paths', os.path.join(REPOS, name))
    return [p for p in listing.splitlines() if p and not p.endswith('/') and p.lower().endswith(CAD)]


def users():
    with open(USERS) as handle:
        return sorted(line.split(':', 1)[0] for line in handle if ':' in line)


def clean_path(text):
    parts = [p.strip() for p in text.replace('\\', '/').split('/') if p.strip()]
    if not parts or not all(SEGMENT.match(p) for p in parts):
        raise Refused('Use folder and file names with letters, numbers, spaces, and _ ( ) . & + , - only.')
    return '/'.join(parts)


def add_to_library(entries, author, message):
    """entries: [(library path, local file)]. New files only; changing existing parts needs Edit/Submit."""
    existing = set(run('svnlook', 'tree', '--full-paths', os.path.join(REPOS, LIBRARY)).splitlines())
    args = ['svnmucc', '--non-interactive', '--username', author, '-m', message, '-U', 'file://' + os.path.join(REPOS, LIBRARY)]
    made = set()
    for target, local in entries:
        if not target.lower().endswith(CAD):
            raise Refused(target + ' is not a SOLIDWORKS part, assembly, or drawing.')
        if target in existing or target.lower() in {p.lower() for p in existing}:
            raise Refused(target + ' already exists in the library. Update it with Edit and Submit instead.')
        parts = target.split('/')
        for i in range(1, len(parts)):
            folder = '/'.join(parts[:i])
            if folder + '/' not in existing and folder not in made:
                args += ['mkdir', folder]
                made.add(folder)
        args += ['put', local, target, 'propset', 'svn:needs-lock', '*', target,
                 'propset', 'svn:mime-type', 'application/octet-stream', target]
    run(*args)


# ---------- undo a submit ----------

def changed_paths(repo, rev):
    """[(action letter, path, is_dir)] for one revision, from svnlook."""
    result = []
    for line in run('svnlook', 'changed', '-r', str(rev), os.path.join(REPOS, repo)).splitlines():
        if len(line) > 4:
            path = line[4:]
            result.append((line[0], path.rstrip('/'), path.endswith('/')))
    return result


def undo_plan(repo, rev):
    """Checks a revision can be undone safely; returns its changes. Never touches files changed again later."""
    if repo not in repositories():
        raise Refused('Unknown repository.')
    if rev < 2 or rev > youngest(repo):
        raise Refused('That revision cannot be undone.')
    changes = changed_paths(repo, rev)
    if not changes:
        raise Refused('r%d changed no files (only properties or nothing).' % rev)
    repo_path = os.path.join(REPOS, repo)
    later = []
    for action, path, is_dir in changes:
        if action == 'D':
            continue
        try:
            history = run('svnlook', 'history', '--limit', '1', repo_path, '/' + path).splitlines()
        except Refused:
            later.append(path)  # Gone now, so something later removed it.
            continue
        latest = next((int(line.split()[0]) for line in history if line.strip() and line.split()[0].isdigit()), rev)
        if latest != rev:
            later.append(path)
    if later:
        raise Refused('Later submits changed %s. Undo those first (newest first), or ask the student to fix it with Edit/Submit.' % ', '.join(later[:5]))
    held = [l for l in locks(repo) if any(l['path'].lstrip('/') == p or l['path'].lstrip('/').startswith(p + '/') for _, p, _ in changes)]
    if held:
        raise Refused('%s is locked by %s. Ask them to Submit or release it first.' % (held[0]['path'], held[0].get('owner', '?')))
    return changes


def undo_submit(user, repo, rev):
    # Pinned to the revision the checks looked at: if a student submits in between, the undo is out of date and
    # fails instead of replacing their newer work.
    head = youngest(repo)
    changes = undo_plan(repo, rev)
    url = 'file://' + os.path.join(REPOS, repo)
    args = ['svnmucc', '--non-interactive', '--username', user, '--with-revprop', 'joco:mentor-undo=%d' % rev,
            '-m', 'Undo r%d (by %s from the admin page)' % (rev, user), '-r', str(head), '-U', url]
    removed_dirs = []
    for action, path, is_dir in sorted(changes, key=lambda c: c[1]):
        if any(path.startswith(d + '/') for d in removed_dirs):
            continue  # Goes away with its added parent folder.
        if action == 'A':
            args += ['rm', path]
            if is_dir:
                removed_dirs.append(path)
        elif action == 'D':
            args += ['cp', str(rev - 1), path, path]
        elif not is_dir:
            # Content and properties exactly as they were before the submit, keeping history.
            args += ['rm', path, 'cp', str(rev - 1), path, path]
    try:
        output = run(*args)
    except Refused as exc:
        if youngest(repo) != head:
            raise Refused('Someone submitted while you were undoing r%d, so nothing was changed. Look at Recent submits and try again.' % rev) from exc
        raise
    match = re.search(r'r(\d+) committed', output)
    return 'Undid r%d in %s as new revision r%s. Students get the previous versions on their next Update.' % (rev, repo, match.group(1) if match else '?')


# ---------- health and add-in check-ins ----------

def read_json(path):
    try:
        with open(path) as handle:
            return json.load(handle)
    except (OSError, ValueError):
        return None


def folder_size(path):
    total = 0
    for root, _, names in os.walk(path):
        for name in names:
            try:
                total += os.lstat(os.path.join(root, name)).st_size
            except OSError:
                pass
    return total


def age_hours(stamp):
    try:
        return (time.time() - calendar.timegm(time.strptime(stamp, '%Y-%m-%dT%H:%M:%SZ'))) / 3600
    except (TypeError, ValueError):
        return None


def record_heartbeat(user, version, computer, solidworks=''):
    if not re.match(r'^\d{1,4}\.\d{1,4}\.\d{1,4}$', version or ''):
        raise Refused('Bad version.')
    computer = re.sub(r'[^A-Za-z0-9._-]', '', computer or '')[:40]
    beats = read_json(HEARTBEATS) or {}
    entry = beats.get(user, {})
    entry.update(version=version, seen=time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime()))
    if re.match(r'^(19|20)\d\d$', solidworks or ''):
        entry['solidworks'] = solidworks
    if computer:
        computers = [c for c in entry.get('computers', []) if c != computer]
        entry['computers'] = ([computer] + computers)[:3]
    beats[user] = entry
    write_atomic(HEARTBEATS, json.dumps(beats, indent=2) + '\n')


# ---------- accounts: students choose their own passwords ----------

def new_setup_code(user, mentor):
    """Disables any current password and creates a one-time setup code; the student picks the password."""
    run('htpasswd', '-B', '-i', USERS, user, stdin=secrets.token_urlsafe(32).encode())  # Unusable until set up.
    code = '-'.join(''.join(secrets.choice(CODE_ALPHABET) for _ in range(4)) for _ in range(3))
    invites = read_json(INVITES) or {}
    invites[user] = {'code': code, 'expires': time.time() + INVITE_DAYS * 86400, 'by': mentor, 'failures': 0}
    write_atomic(INVITES, json.dumps(invites, indent=2) + '\n', 0o600)
    return code


def new_open_code(mentor, make_mentor):
    """A setup code not tied to a name: the student chooses their own username (and password) with it."""
    code = new_code()
    invites = read_json(INVITES) or {}
    invites['open:' + secrets.token_hex(6)] = {'code': code, 'expires': time.time() + INVITE_DAYS * 86400, 'by': mentor, 'mentor': bool(make_mentor)}
    write_atomic(INVITES, json.dumps(invites, indent=2) + '\n', 0o600)
    return code


def open_codes():
    """Unused, unexpired codes that let a student pick their own username: [(id, invite)]."""
    now = time.time()
    return [(k[5:], v) for k, v in sorted((read_json(INVITES) or {}).items(), key=lambda kv: kv[1]['expires'])
            if k.startswith('open:') and v['expires'] > now]


def _throttle(address, kind='setup'):
    # Generous: a whole team setting up at school shares one public address. Codes are 12 random characters,
    # and five wrong guesses kill a code, so this only slows down scripts.
    now = time.time()
    key = kind + ':' + (address or '')
    recent = [t for t in _setup_attempts.get(key, []) if now - t < 3600]
    if len(recent) >= 60:
        raise Refused('Too many attempts from this network. Try again in an hour.')
    _setup_attempts[key] = recent + [now]


def _password_rule(user, password):
    if len(password) < 10 or password.lower() == user:
        raise Refused('Choose a password of at least 10 characters that isn\'t your username.')


def _password_matches(user, hashed, password):
    """bcrypt check through htpasswd itself (Python has no bcrypt here), against a one-line temporary file."""
    with tempfile.NamedTemporaryFile('w', dir=CONFIG, prefix='.verify-', delete=True) as handle:
        handle.write(user + ':' + hashed + '\n')
        handle.flush()
        return subprocess.run(['htpasswd', '-v', '-i', handle.name, user], input=password.encode(), capture_output=True).returncode == 0


def pending_requests():
    now = time.time()
    return {k: v for k, v in (read_json(REQUESTS) or {}).items() if v['expires'] > now}


def request_account(address, user, password):
    """Public (no sign-in): a student asks for an account with the username and password they chose. Nothing works
    until a mentor hands them the code shown on the Accounts tab; activating needs that code and this password."""
    _throttle(address, 'request')
    user = (user or '').strip().lower()
    if not USERNAME.match(user) or user == PUBLISHER:
        raise Refused('Usernames: 2–32 lowercase letters, numbers, dot, dash, underscore, starting with a letter or number.')
    if user in users():
        raise Refused('The username ' + user + ' is taken. Choose another one (or, if it\'s yours, ask a mentor for a New setup code).')
    _password_rule(user, password)
    requests = pending_requests()
    existing = requests.get(user)
    if existing:
        if _password_matches(user, existing['hash'], password):
            return  # Asked twice: same request, same code.
        raise Refused('Someone already asked for the username ' + user + '. Choose another one, or ask a mentor.')
    if len(requests) >= MAX_REQUESTS:
        raise Refused('Too many account requests are waiting. Ask a mentor.')
    hashed = run('htpasswd', '-niB', user, stdin=password.encode()).strip().split(':', 1)[1]
    requests[user] = {'hash': hashed, 'code': new_code(), 'at': time.time(), 'expires': time.time() + INVITE_DAYS * 86400,
                      'address': re.sub(r'[^0-9a-fA-F.:]', '', address or '')[:45], 'failures': 0}
    write_atomic(REQUESTS, json.dumps(requests, indent=2) + '\n', 0o600)


def new_code():
    return '-'.join(''.join(secrets.choice(CODE_ALPHABET) for _ in range(4)) for _ in range(3))


def claim_account(address, user, code, password):
    """Public (no sign-in): a student turns a setup code into their own password. Deliberately vague errors."""
    now = time.time()
    _throttle(address)
    user = (user or '').strip().lower()
    code = re.sub(r'[^A-Z0-9]', '', (code or '').upper())
    # A student's own request: the mentor's code plus the password they asked with.
    requests = pending_requests()
    asked = requests.get(user)
    if asked and user not in users():
        if not hmac.compare_digest(asked['code'].replace('-', ''), code):
            asked['failures'] = asked.get('failures', 0) + 1
            if asked['failures'] >= 5:
                del requests[user]  # Guessing: the request is dead; the student asks again.
            write_atomic(REQUESTS, json.dumps(requests, indent=2) + '\n', 0o600)
            raise Refused('That code isn\'t the one for ' + user + '. Check it with your mentor.')
        if not _password_matches(user, asked['hash'], password):
            raise Refused('Use the same password you asked with. (If someone else asked for ' + user + ', ask a mentor to reject that request.)')
        run('htpasswd', '-B', '-i', USERS, user, stdin=password.encode())
        del requests[user]
        write_atomic(REQUESTS, json.dumps(requests, indent=2) + '\n', 0o600)
        return
    invites = read_json(INVITES) or {}
    invite = invites.get(user)
    matches = lambda i: i['expires'] >= now and hmac.compare_digest(i['code'].replace('-', ''), code)
    if not (invite and matches(invite)):
        # A code not tied to a name: this student is choosing their username now. Only someone holding a valid code
        # learns whether a name is taken.
        key = next((k for k, v in invites.items() if k.startswith('open:') and matches(v)), None)
        if key is not None:
            if not USERNAME.match(user) or user == PUBLISHER:
                raise Refused('Usernames: 2–32 lowercase letters, numbers, dot, dash, underscore, starting with a letter or number.')
            if user in users():
                raise Refused('The username ' + user + ' is taken. Choose another one.')
            if len(password) < 10 or password.lower() == user:
                raise Refused('Choose a password of at least 10 characters that isn\'t your username.')
            run('htpasswd', '-B', '-i', USERS, user, stdin=password.encode())
            if invites[key].get('mentor'):
                state = load_state()
                state['mentors'] = sorted(set(state['mentors']) | {user})
                save_state(state)
            del invites[key]
            write_atomic(INVITES, json.dumps(invites, indent=2) + '\n', 0o600)
            return
        if invite:
            invite['failures'] = invite.get('failures', 0) + 1
            if invite['failures'] >= 5:
                del invites[user]  # Guessing: the code is dead; a mentor makes a new one.
            write_atomic(INVITES, json.dumps(invites, indent=2) + '\n', 0o600)
        raise Refused('That username and setup code don\'t match, or the code expired. Ask a mentor for a new code.')
    if len(password) < 10 or password.lower() == user:
        raise Refused('Choose a password of at least 10 characters that isn\'t your username.')
    run('htpasswd', '-B', '-i', USERS, user, stdin=password.encode())
    del invites[user]
    write_atomic(INVITES, json.dumps(invites, indent=2) + '\n', 0o600)


def change_password(user, password):
    if len(password) < 10 or password.lower() == user:
        raise Refused('Choose a password of at least 10 characters that isn\'t your username.')
    run('htpasswd', '-B', '-i', USERS, user, stdin=password.encode())


# ---------- actions (all run under Locked) ----------

def act(user, form):
    action = form.get('action', '')
    state = load_state()
    if action == 'create-season':
        name = form.get('name', '').strip()
        if not SEASON.match(name):
            raise Refused('Season names look like 2028-Robot.')
        create_repository(name, ROBOT_FOLDERS, user, 'Create canonical robot folders')
        if form.get('activate'):
            state['active'] = name
        save_state(state)
        return 'Created ' + name + '.'
    if action == 'set-master':
        name, master = form.get('name', ''), form.get('master', '').strip().strip('/').replace('\\', '/')
        if name not in repositories() or not SEASON.match(name):
            raise Refused('Unknown season.')
        if master:
            if not master.lower().endswith('.sldasm') or subprocess.run(['svnlook', 'filesize', os.path.join(REPOS, name), master], capture_output=True).returncode != 0:
                raise Refused(master + ' is not an assembly in ' + name + '. Use the path inside the season, like Clean Robot CAD/2026ASSembly4.SLDASM.')
            state.setdefault('masters', {})[name] = master
        else:
            state.setdefault('masters', {}).pop(name, None)
        save_state(state)
        return 'Open Robot in %s now opens %s.' % (name, master or 'the automatic choice (00_Master/Robot.SLDASM)')
    if action == 'delete-season':
        name = form.get('name', '')
        if name not in repositories() or not SEASON.match(name):
            raise Refused('Unknown season.')
        if name == state['active']:
            raise Refused('Make another season active before deleting ' + name + '.')
        # Only a season nobody has submitted to: revision 1 is the folder creation.
        if has_files(name) or youngest(name) > 1 or locks(name):
            raise Refused(name + ' has files or history, so it cannot be deleted. Archive it instead.')
        stamp = time.strftime('%Y%m%dT%H%M%SZ', time.gmtime())
        os.rename(os.path.join(REPOS, name), os.path.join(REPOS, '.deleted-%s-%s' % (name, stamp)))
        state['archived'] = [n for n in state['archived'] if n != name]
        save_state(state)
        return 'Deleted empty season ' + name + '.'
    if action in ('activate', 'archive', 'unarchive'):
        name = form.get('name', '')
        if name not in repositories() or not SEASON.match(name):
            raise Refused('Unknown season.')
        note = ''
        if action == 'activate':
            if name in state['archived']:
                raise Refused('Unarchive ' + name + ' before making it active.')
            previous = state['active']
            held = locks(previous) if previous in repositories() and previous != name else []
            if held:
                # Not refused: the add-in keeps those students on the old season until their work is submitted.
                note = ' Note: %s still has %d locked file(s) (%s); those students stay on %s until they Submit or Set Aside.' % (
                    previous, len(held), ', '.join(sorted({l.get('owner', '?') for l in held})), previous)
            state['active'] = name
        elif action == 'archive':
            if name == state['active']:
                raise Refused('Make another season active before archiving ' + name + '.')
            if locks(name):
                raise Refused(name + ' still has locked files. Ask students to Submit, or release the locks first.')
            state['archived'] = sorted(set(state['archived']) | {name})
        else:
            state['archived'] = [n for n in state['archived'] if n != name]
        save_state(state)
        return {'activate': 'Students now open ' + name + '.' + note, 'archive': name + ' is read-only.', 'unarchive': name + ' is editable again.'}[action]
    if action == 'set-solidworks':
        year = form.get('year', '').strip()
        if year and not re.match(r'^20\d\d$', year):
            raise Refused('Enter a year like 2026, or leave it empty to allow any version.')
        state['solidworks'] = year or None
        save_state(state)
        return ('Approved SOLIDWORKS version: %s. Newer versions can look but not edit or submit.' % year) if year else 'Any SOLIDWORKS version may edit.'
    if action == 'release-lock':
        repo, path = form.get('repo', ''), form.get('path', '')
        if not form.get('confirmed'):
            raise Refused('Tick the box first: releasing does not keep that student\'s unsubmitted changes.')
        if repo not in repositories() or not any(l['path'] == path for l in locks(repo)):
            raise Refused('That lock no longer exists.')
        # rmlocks bypasses the student pre-unlock hook; unsubmitted edits on the owner's PC become stale.
        run('svnadmin', 'rmlocks', os.path.join(REPOS, repo), path)
        return 'Released ' + path + '. The previous owner can no longer submit their unsaved copy of it.'
    if action == 'add-user' and not form.get('username', '').strip():
        new_open_code(user, form.get('mentor'))
        return ('New ' + ('mentor ' if form.get('mentor') else '') + 'setup code made; it\'s listed under Unused setup codes. '
                'Give it to the student: they choose their own username and password in SOLIDWORKS.')
    if action == 'reject-request':
        requests = pending_requests()
        name = form.get('username', '')
        if requests.pop(name, None) is None:
            raise Refused('That request was already used or rejected.')
        write_atomic(REQUESTS, json.dumps(requests, indent=2) + '\n', 0o600)
        return 'Rejected the request for ' + name + '.'
    if action == 'cancel-code':
        invites = read_json(INVITES) or {}
        if invites.pop('open:' + form.get('id', ''), None) is None:
            raise Refused('That code was already used or cancelled.')
        write_atomic(INVITES, json.dumps(invites, indent=2) + '\n', 0o600)
        return 'Setup code cancelled.'
    if action in ('add-user', 'reset-password'):
        name = form.get('username', '').strip().lower()
        if not USERNAME.match(name):
            raise Refused('Usernames: 2–32 lowercase letters, numbers, dot, dash, underscore.')
        if name == PUBLISHER:
            raise Refused(PUBLISHER + ' is the GitHub release account.')
        if (action == 'add-user') == (name in users()):
            raise Refused(name + (' already exists.' if action == 'add-user' else ' does not exist.'))
        new_setup_code(name, user)
        if action == 'add-user' and form.get('mentor'):
            state['mentors'] = sorted(set(state['mentors']) | {name})
            save_state(state)
        # The code is shown on the Accounts page, never in a URL or log.
        return ('Added ' + name + '.' if action == 'add-user' else name + '\'s old password no longer works.') + \
            ' Give them the setup code shown next to their name; they choose their own password in SOLIDWORKS.'
    if action in ('delete-user', 'toggle-mentor'):
        name = form.get('username', '')
        if name not in users():
            raise Refused('Unknown user.')
        if name == user:
            raise Refused('You cannot remove your own account or mentor role.')
        if name == PUBLISHER and action == 'toggle-mentor':
            raise Refused(PUBLISHER + ' is the GitHub release uploader and cannot be a mentor.')
        if action == 'delete-user':
            held = [l for r in repositories() for l in locks(r) if l.get('owner') == name]
            if held:
                raise Refused(name + ' still holds ' + str(len(held)) + ' lock(s). Release them first.')
            run('htpasswd', '-D', USERS, name)
            state['mentors'] = [m for m in state['mentors'] if m != name]
            save_state(state)
            return 'Deleted ' + name + '. Their history is kept.'
        state['mentors'] = sorted(set(state['mentors']) ^ {name})
        save_state(state)
        return name + (' is now a mentor.' if name in state['mentors'] else ' is no longer a mentor.')
    if action in ('release-staged', 'discard-staged'):
        staged = state.get('staged_addin')
        if not staged:
            raise Refused('Nothing is staged.')
        path = os.path.join(UPDATES, 'staged', staged['file'])
        if action == 'discard-staged':
            shutil.rmtree(os.path.join(UPDATES, 'staged'), ignore_errors=True)
            state.pop('staged_addin', None)
            save_state(state)
            return 'Discarded staged ' + staged['version'] + '.'
        with open(path, 'rb') as handle:
            data = handle.read()
        if hashlib.sha256(data).hexdigest() != staged['sha256']:
            raise Refused('The staged file changed on the server. Discard it and re-run the GitHub release.')
        return release_addin(staged['file'], data, form.get('required'))
    if action == 'undo-submit':
        try:
            rev = int(form.get('rev', ''))
        except ValueError:
            raise Refused('Unknown revision.')
        return undo_submit(user, form.get('repo', ''), rev)
    if action == 'addin-required':
        if not state.get('addin'):
            raise Refused('No add-in has been published yet.')
        state['addin']['required'] = not state['addin'].get('required')
        save_state(state)
        return 'Add-in %s is now %s.' % (state['addin']['version'], 'required' if state['addin']['required'] else 'optional')
    if action == 'promote':
        repo, _, source = form.get('choice', '').partition('|')
        if repo not in repositories() or not SEASON.match(repo) or source not in files(repo):
            raise Refused('Choose a CAD file from a season.')
        target = clean_path(form.get('folder', '') + '/' + source.rsplit('/', 1)[-1])
        with tempfile.NamedTemporaryFile() as temp:
            temp.write(subprocess.run(['svnlook', 'cat', os.path.join(REPOS, repo), source], capture_output=True, check=True).stdout)
            temp.flush()
            add_to_library([(target, temp.name)], user, 'Add %s from %s:/%s' % (target, repo, source))
        return 'Added ' + target + ' to the library.'
    raise Refused('Unknown action.')


def version_key(text):
    return tuple(int(x) for x in text.split('.'))


def check_installer(name, data, expected_sha=None):
    """Returns (version, sha256) for an installer that is safe to offer, or raises Refused."""
    match = INSTALLER.match(name)
    if not match:
        raise Refused('Use the file made by Build-Installer.ps1 or GitHub, named like JOCO-ROBOS-CAD-Setup-0.6.0.exe.')
    if not data.startswith(b'MZ'):
        raise Refused(name + ' is not a Windows program.')
    digest = hashlib.sha256(data).hexdigest()
    if expected_sha and digest != expected_sha.strip().lower():
        raise Refused('%s does not match the expected SHA-256 (got %s, %.1f MB). The download was probably incomplete; download it again.'
                      % (name, digest, len(data) / 1048576.0))
    version = '.'.join(match.groups())
    current = load_state().get('addin')
    if current and version_key(version) <= version_key(current['version']):
        raise Refused('Version %s is not newer than the published %s. Bump <Version> in the .csproj and rebuild.' % (version, current['version']))
    return version, digest


def store(folder, name, data):
    os.makedirs(folder, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=folder, delete=False) as handle:
        handle.write(data)
    os.chmod(handle.name, 0o644)
    os.replace(handle.name, os.path.join(folder, name))


def release_addin(name, data, required):
    version, digest = check_installer(name, data)
    store(UPDATES, name, data)
    state = load_state()
    state['addin'] = {'version': version, 'file': name, 'sha256': digest, 'required': bool(required), 'size': len(data)}
    state.pop('staged_addin', None)
    save_state(state)
    # Keep the three newest installers so students mid-download are not cut off.
    old = sorted((f for f in os.listdir(UPDATES) if INSTALLER.match(f)), key=lambda f: version_key('.'.join(INSTALLER.match(f).groups())))
    for stale in old[:-3]:
        os.remove(os.path.join(UPDATES, stale))
    shutil.rmtree(os.path.join(UPDATES, 'staged'), ignore_errors=True)
    return 'Published add-in %s%s. Students are offered it the next time SOLIDWORKS checks.' % (version, ' as a required update' if required else '')


def stage_addin(name, data, expected_sha):
    """Called by GitHub Actions: holds a verified installer until a mentor releases it."""
    if not expected_sha:
        raise Refused('Missing SHA-256.')
    version, digest = check_installer(name, data, expected_sha)
    shutil.rmtree(os.path.join(UPDATES, 'staged'), ignore_errors=True)
    os.makedirs(os.path.join(UPDATES, 'staged'), mode=0o700)
    store(os.path.join(UPDATES, 'staged'), name, data)
    state = load_state()
    state['staged_addin'] = {'version': version, 'file': name, 'sha256': digest, 'size': len(data), 'at': time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}
    save_state(state)
    return 'Staged %s for mentor release.' % version


def publish_addin(fields):
    uploads = fields.get('files', [])
    if len(uploads) != 1:
        raise Refused('Choose one JOCO-ROBOS-CAD-Setup-x.y.z.exe file.')
    name, data = os.path.basename(uploads[0][0].replace('\\', '/')), uploads[0][1]
    check_installer(name, data, fields.get('sha256', b'').decode('ascii', 'replace') or None)
    return release_addin(name, data, fields.get('required'))


def upload(user, fields):
    if fields.get('kind') == b'addin':
        return publish_addin(fields)
    folder = clean_path(fields.get('folder', b'').decode('utf-8', 'replace') or 'Hardware')
    message = fields.get('comment', b'').decode('utf-8', 'replace').strip() or 'Add parts to library'
    uploads = [(clean_path(folder + '/' + os.path.basename(name.replace('\\', '/'))), data) for name, data in fields.get('files', [])]
    if not uploads:
        raise Refused('Choose one or more SOLIDWORKS files.')
    with tempfile.TemporaryDirectory() as scratch:
        entries = []
        for i, (target, data) in enumerate(uploads):
            local = os.path.join(scratch, str(i))
            with open(local, 'wb') as handle:
                handle.write(data)
            entries.append((target, local))
        add_to_library(entries, user, message)
    return 'Added %d file(s) to the library.' % len(uploads)


# ---------- web page ----------

STYLE = '''
:root{--bg:#f6f7f9;--card:#fff;--ink:#16181d;--muted:#5d6470;--line:#dde1e7;--accent:#1f5fbf;--ok:#1d7a46;--warn:#9a5b00;--bad:#b3261e}
@media (prefers-color-scheme:dark){:root{--bg:#121417;--card:#1b1e23;--ink:#e8eaee;--muted:#9aa2ad;--line:#2c3139;--accent:#79a8f0;--ok:#5cc28a;--warn:#e0a84a;--bad:#f08079}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,Segoe UI,sans-serif}
header{display:flex;gap:20px;align-items:center;flex-wrap:wrap;padding:14px 20px;border-bottom:1px solid var(--line);background:var(--card)}
header b{font-size:17px}nav a{margin-right:14px;color:var(--muted);text-decoration:none}nav a.on{color:var(--ink);font-weight:600}
main{max-width:1050px;margin:0 auto;padding:20px 16px}section{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin-bottom:18px}
h2{font-size:16px;margin:0 0 12px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:7px 8px;border-top:1px solid var(--line);vertical-align:top}
th{color:var(--muted);font-weight:500;font-size:13px;border-top:0}.muted{color:var(--muted)}.tag{font-size:12px;padding:1px 7px;border-radius:9px;border:1px solid var(--line)}
.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}form.inline{display:inline}
input,select,button{font:inherit;padding:6px 9px;border:1px solid var(--line);border-radius:6px;background:var(--bg);color:var(--ink)}
button{cursor:pointer;background:var(--card)}button.primary{background:var(--accent);border-color:var(--accent);color:#fff}
.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin-top:8px}.notice{padding:10px 14px;border-radius:8px;margin-bottom:16px;border:1px solid var(--line);background:var(--card)}
code{font-size:13px}.scroll{overflow-x:auto}
'''


def esc(value):
    return html.escape(str(value), quote=True)


class Admin(BaseHTTPRequestHandler):
    server_version = 'JocoAdmin'

    def log_message(self, fmt, *args):
        sys.stderr.write('admin: %s %s\n' % (self.headers.get('X-Joco-User', '-'), fmt % args))

    @property
    def user(self):
        return self.headers.get('X-Joco-User', '')

    def token(self):
        with open(SECRET) as handle:
            return hmac.new(handle.read().encode(), self.user.encode(), hashlib.sha256).hexdigest()

    def guard(self):
        state = load_state()
        if not self.user or self.user not in state['mentors']:
            self.page('Mentors only', '<section><h2>Mentors only</h2><p>This page is for mentors. Students do everything from SOLIDWORKS.</p></section>', '', status=403)
            return None
        return state

    # ---------- FRCDesignLib API for the add-in (any signed-in student) ----------

    def frc_api(self, method):
        path = urlsplit(self.path).path
        if not self.user or self.user == PUBLISHER or self.headers.get('X-Joco-Client') != 'addin':
            return self.reply(403, 'Not allowed.')
        try:
            parts = path[len('/admin/api/frcdesign/'):].split('/')
            if method == 'GET' and parts[0] == 'search':
                return self.json_reply({'results': frcdesign.search(parse_qs(urlsplit(self.path).query).get('q', [''])[0])})
            if method == 'GET' and parts[0] == 'item' and len(parts) == 2:
                return self.json_reply(frcdesign.details(parts[1]))
            if method == 'GET' and parts[0] == 'thumb' and len(parts) == 2:
                size = parse_qs(urlsplit(self.path).query).get('size', ['300x300'])[0]
                data, kind = frcdesign.thumbnail(parts[1], '70x40' if size == '70x40' else '300x300')
                return self.bytes_reply(data, kind, 'public, max-age=86400')
            if method == 'GET' and parts[0] == 'download' and len(parts) == 2:
                data, name = frcdesign.download(self.user, parts[1], self.headers.get('X-Joco-Token', ''))
                return self.bytes_reply(data, 'application/octet-stream', 'no-store', name)
            if method == 'POST' and parts[0] in ('claim', 'complete', 'abandon'):
                body = json.loads(self.rfile.read(min(int(self.headers.get('Content-Length', '0')), 65536)) or b'{}')
                with Locked():
                    if parts[0] == 'claim':
                        return self.json_reply(frcdesign.claim(self.user, str(body.get('id', '')), body.get('configuration') or {},
                                                               str(body.get('client', ''))[:64]))
                    if parts[0] == 'complete':
                        return self.json_reply(frcdesign.complete(self.user, str(body.get('fingerprint', '')), str(body.get('token', ''))))
                    return self.json_reply(frcdesign.abandon(self.user, str(body.get('fingerprint', '')), str(body.get('token', ''))))
            return self.reply(404, 'Unknown request.')
        except frcdesign.FrcError as exc:
            return self.reply(exc.status, str(exc))
        except ValueError:
            return self.reply(400, 'Bad request.')

    def json_reply(self, value):
        return self.bytes_reply(json.dumps(value).encode(), 'application/json', 'no-store')

    def bytes_reply(self, data, kind, cache, filename=None):
        self.send_response(200)
        self.send_header('Content-Type', kind)
        self.send_header('Content-Length', str(len(data)))
        self.send_header('Cache-Control', cache)
        if filename:
            self.send_header('Content-Disposition', 'attachment; filename="%s"' % re.sub(r'[^A-Za-z0-9 ._()&+,-]', '_', filename))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self):
        if urlsplit(self.path).path.startswith('/admin/api/frcdesign/'):
            return self.frc_api('GET')
        state = self.guard()
        if state is None:
            return
        path = urlsplit(self.path).path.rstrip('/')
        query = parse_qs(urlsplit(self.path).query)
        notice = query.get('ok', [''])[0]
        error = query.get('error', [''])[0]
        self.query = query
        pages = {'/admin': self.home, '/admin/locks': self.locks_page, '/admin/library': self.library_page, '/admin/users': self.users_page,
                 '/admin/addin': self.addin_page, '/admin/undo': self.undo_page}
        if path not in pages:
            self.send_error(404)
            return
        try:
            body = pages[path](state)
        except Refused as exc:
            body, error = '', str(exc)
        banner = ''
        if notice:
            banner = '<div class="notice ok">' + esc(notice) + '</div>'
        if error:
            banner = '<div class="notice bad">' + esc(error) + '</div>'
        self.page({'/admin': 'Seasons', '/admin/locks': 'Locks', '/admin/library': 'Library', '/admin/users': 'Accounts', '/admin/addin': 'Add-in',
                   '/admin/undo': 'Undo a submit'}[path], banner + body, path)

    def do_POST(self):
        if urlsplit(self.path).path == '/admin/api/stage-addin':
            return self.stage()
        if urlsplit(self.path).path == '/admin/api/heartbeat':
            return self.heartbeat()
        if urlsplit(self.path).path.startswith('/admin/api/frcdesign/'):
            return self.frc_api('POST')
        if urlsplit(self.path).path == '/account/setup':
            return self.account_setup()
        if urlsplit(self.path).path == '/account/request':
            return self.account_request()
        if urlsplit(self.path).path == '/admin/api/password':
            return self.password_change()
        state = self.guard()
        if state is None:
            return
        back = urlsplit(self.path).path.rstrip('/') or '/admin'
        if back not in ('/admin', '/admin/locks', '/admin/library', '/admin/users', '/admin/addin'):
            back = '/admin'
        try:
            # Browsers resend Basic credentials automatically: require same-origin plus a per-user token.
            origin = self.headers.get('Origin') or self.headers.get('Referer') or ''
            host = self.headers.get('X-Forwarded-Host', self.headers.get('Host', '')).split(',')[0].strip()
            if urlsplit(origin).netloc != host:
                raise Refused('Request blocked: it did not come from this page.')
            length = int(self.headers.get('Content-Length', '0'))
            if length > MAX_UPLOAD + 65536:
                raise Refused('Upload is larger than 100 MB. Add big assemblies from SOLIDWORKS with Submit instead.')
            raw = self.rfile.read(length)
            kind = self.headers.get('Content-Type', '')
            if kind.startswith('multipart/form-data'):
                fields = self.multipart(kind, raw)
                if not hmac.compare_digest(fields.get('token', b'').decode(), self.token()):
                    raise Refused('Your page expired. Reload and try again.')
                with Locked():
                    message = upload(self.user, fields)
            else:
                form = {k: v[0] for k, v in parse_qs(raw.decode('utf-8'), keep_blank_values=True).items()}
                if not hmac.compare_digest(form.get('token', ''), self.token()):
                    raise Refused('Your page expired. Reload and try again.')
                with Locked():
                    message = act(self.user, form)
            self.redirect(back + '?ok=' + quote(message))
        except Refused as exc:
            self.redirect(back + '?error=' + quote(str(exc)[:600]))

    def stage(self):
        # Only the GitHub release account; it has no mentor page and no SVN access.
        if self.user != PUBLISHER:
            return self.reply(403, 'Only the GitHub release account can stage installers.')
        try:
            length = int(self.headers.get('Content-Length', '0'))
            if length > MAX_UPLOAD:
                raise Refused('Installer is larger than 100 MB.')
            data = self.rfile.read(length)
            with Locked():
                message = stage_addin(os.path.basename(self.headers.get('X-Joco-File', '')), data, self.headers.get('X-Joco-Sha256', ''))
            self.reply(200, message)
        except Refused as exc:
            self.reply(400, str(exc))

    def heartbeat(self):
        # Any student's add-in reports its version. The custom header can't be sent cross-site without CORS approval.
        if not self.user or self.user == PUBLISHER or self.headers.get('X-Joco-Client') != 'addin':
            return self.reply(403, 'Not allowed.')
        try:
            body = json.loads(self.rfile.read(min(int(self.headers.get('Content-Length', '0')), 4096)) or b'{}')
            with Locked():
                record_heartbeat(self.user, str(body.get('version', '')), str(body.get('computer', '')), str(body.get('solidworks', '')))
            self.reply(200, 'ok')
        except (Refused, ValueError) as exc:
            self.reply(400, str(exc))

    def account_setup(self):
        # Reached without sign-in (see svn.conf /account); only a valid setup code can set a password.
        address = self.headers.get('CF-Connecting-IP') or self.headers.get('X-Forwarded-For', '').split(',')[0].strip() or self.client_address[0]
        try:
            body = json.loads(self.rfile.read(min(int(self.headers.get('Content-Length', '0')), 4096)) or b'{}')
            with Locked():
                claim_account(address, str(body.get('username', '')), str(body.get('code', '')), str(body.get('password', '')))
            self.reply(200, 'Your password is set.')
        except (Refused, ValueError) as exc:
            self.reply(400, str(exc) if isinstance(exc, Refused) else 'Bad request.')

    def account_request(self):
        # Reached without sign-in (see svn.conf /account); only stores a request, which does nothing without a mentor's code.
        address = self.headers.get('CF-Connecting-IP') or self.headers.get('X-Forwarded-For', '').split(',')[0].strip() or self.client_address[0]
        try:
            body = json.loads(self.rfile.read(min(int(self.headers.get('Content-Length', '0')), 4096)) or b'{}')
            with Locked():
                request_account(address, str(body.get('username', '')), str(body.get('password', '')))
            self.reply(200, 'Request sent. Ask a mentor for your code.')
        except (Refused, ValueError) as exc:
            self.reply(400, str(exc) if isinstance(exc, Refused) else 'Bad request.')

    def password_change(self):
        # Apache already checked the current password; the add-in header blocks cross-site form posts.
        if not self.user or self.user == PUBLISHER or self.headers.get('X-Joco-Client') != 'addin':
            return self.reply(403, 'Not allowed.')
        try:
            body = json.loads(self.rfile.read(min(int(self.headers.get('Content-Length', '0')), 4096)) or b'{}')
            with Locked():
                change_password(self.user, str(body.get('password', '')))
            self.reply(200, 'Password changed.')
        except (Refused, ValueError) as exc:
            self.reply(400, str(exc) if isinstance(exc, Refused) else 'Bad request.')

    def reply(self, status, text):
        data = (text + '\n').encode()
        self.send_response(status)
        self.send_header('Content-Type', 'text/plain; charset=utf-8')
        self.send_header('Content-Length', str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    @staticmethod
    def multipart(kind, raw):
        message = BytesParser(policy=HTTP).parsebytes(b'Content-Type: ' + kind.encode() + b'\r\n\r\n' + raw)
        fields = {'files': []}
        for part in message.iter_parts():
            name = part.get_param('name', header='content-disposition')
            if part.get_filename():
                if part.get_filename().strip():
                    fields['files'].append((part.get_filename(), part.get_payload(decode=True)))
            elif name:
                fields[name] = part.get_payload(decode=True) or b''
        return fields

    def redirect(self, location):
        self.send_response(303)
        self.send_header('Location', location)
        self.send_header('Content-Length', '0')
        self.end_headers()

    def page(self, title, body, current, status=200):
        links = [('/admin', 'Seasons'), ('/admin/locks', 'Locks'), ('/admin/library', 'Library'), ('/admin/users', 'Accounts'), ('/admin/addin', 'Add-in')]
        nav = ''.join('<a href="%s"%s>%s</a>' % (h, ' class="on"' if h == current else '', t) for h, t in links)
        text = ('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
                '<title>%s · JOCO ROBOS CAD</title><style>%s</style></head><body><header><b>JOCO ROBOS CAD</b><nav>%s</nav>'
                '<span class="muted">%s</span></header><main>%s</main></body></html>') % (esc(title), STYLE, nav, esc(self.user), body)
        data = text.encode()
        self.send_response(status)
        self.send_header('Content-Type', 'text/html; charset=utf-8')
        self.send_header('Content-Length', str(len(data)))
        self.send_header('Cache-Control', 'no-store')
        self.send_header('X-Frame-Options', 'DENY')
        self.send_header('Content-Security-Policy', "default-src 'none'; style-src 'unsafe-inline'; form-action 'self'")
        self.end_headers()
        self.wfile.write(data)

    def form(self, action, fields, label, extra='', primary=False, confirm=None):
        hidden = ''.join('<input type="hidden" name="%s" value="%s">' % (esc(k), esc(v)) for k, v in fields.items())
        return ('<form class="inline" method="post"><input type="hidden" name="token" value="%s"><input type="hidden" name="action" value="%s">%s%s'
                '<button%s>%s</button></form>') % (self.token(), esc(action), hidden, extra, ' class="primary"' if primary else '', esc(label))

    def home(self, state):
        seasons = [n for n in repositories() if SEASON.match(n)]
        rows = ''
        for name in reversed(seasons):
            held = locks(name)
            if name == state['active']:
                status, actions = '<span class="ok">● Active — students open this</span>', ''
            elif name in state['archived']:
                status, actions = '<span class="muted">Archived (read-only)</span>', self.form('unarchive', {'name': name}, 'Unarchive')
            else:
                status = '<span class="warn">Editable, not active</span>'
                actions = self.form('activate', {'name': name}, 'Make active') + ' ' + self.form('archive', {'name': name}, 'Archive')
                if youngest(name) <= 1 and not held and not has_files(name):
                    actions += ' ' + self.form('delete-season', {'name': name}, 'Delete (empty)')
            master = state.get('masters', {}).get(name, '')
            master_form = ('<form class="inline" method="post"><input type="hidden" name="token" value="%s"><input type="hidden" name="action" value="set-master">'
                           '<input type="hidden" name="name" value="%s"><input name="master" value="%s" placeholder="00_Master/Robot.SLDASM (automatic)" size="34" '
                           'aria-label="Master assembly for %s"> <button>Set</button></form>') % (self.token(), esc(name), esc(master), esc(name))
            rows += '<tr><td><b>%s</b></td><td>r%d</td><td>%d</td><td>%s</td><td>%s<div class="muted" style="margin-top:6px">Open Robot opens: %s</div></td></tr>' % (
                esc(name), youngest(name), len(held), status, actions, master_form)
        next_year = (int(seasons[-1][:4]) + 1) if seasons else 2027
        create = ('<form method="post" class="row"><input type="hidden" name="token" value="%s"><input type="hidden" name="action" value="create-season">'
                  '<input name="name" value="%d-Robot" pattern="(19|20)[0-9]{2}-Robot" required aria-label="Season name">'
                  '<label><input type="checkbox" name="activate" value="1"> Make it active now</label><button class="primary">Create season</button></form>'
                  '<p class="muted">Creates the standard subsystem folders with lock rules and daily backups. Students switch automatically the next time they click Open Robot or Update. '
                  'Reuse parts by adding them to the Library; students insert them with “Insert from Library”.</p>') % (self.token(), next_year)
        recent = activity(seasons[-2:] + [LIBRARY])
        log = ''.join('<tr><td>%s</td><td class="muted">%s r%d</td><td>%s</td><td>%s<div class="muted">%s</div></td><td>%s</td></tr>' % (
            esc(e['date']), esc(e['repo']), e['rev'], esc(e['author']), esc(e['msg']),
            esc(', '.join(f.rsplit('/', 1)[-1] for f in e['files'][:6]) + (' …' if len(e['files']) > 6 else '')),
            '<a href="/admin/undo?repo=%s&amp;rev=%d">Undo…</a>' % (quote(e['repo']), e['rev']) if e['rev'] > 1 and e['files'] else '') for e in recent)
        return (self.health() + '<section><h2>Robot seasons</h2><div class="scroll"><table><tr><th>Season</th><th>Revision</th><th>Locks</th><th>Status</th><th></th></tr>%s</table></div></section>'
                '<section><h2>Start a new season</h2>%s</section>'
                '<section><h2>Recent submits</h2><div class="scroll"><table><tr><th>When (UTC)</th><th>Where</th><th>Who</th><th>What</th><th></th></tr>%s</table></div></section>') % (
                    rows or '<tr><td colspan="5" class="muted">No seasons yet.</td></tr>', create, log or '<tr><td colspan="5" class="muted">Nothing yet.</td></tr>')

    def health(self):
        disk = os.statvfs(REPOS)
        free, total = disk.f_bavail * disk.f_frsize, disk.f_blocks * disk.f_frsize
        items = []
        def item(ok, text):
            items.append('<li class="%s">%s %s</li>' % ('ok' if ok else 'bad', '✓' if ok else '⚠', text))
        item(True, 'Server and SVN are responding')
        for name, label, limit in (('backup.json', 'Deck backup', 36), ('offsite.json', 'Off-device backup', 72),
                                   ('restore-test.json', 'Last restore drill (server/restore-drill.sh)', 24 * 200)):
            data = read_json(os.path.join(HEALTH, name)) or {}
            hours = age_hours(data.get('time'))
            if hours is None:
                item(False, label + ': no record yet')
            else:
                item(hours <= limit, '%s: %s (%s)' % (label, esc(data.get('time', '').replace('T', ' ').replace('Z', ' UTC')),
                                                     'today' if hours < 24 else '%d days ago' % (hours // 24)))
        item(free / float(total) > 0.15, 'Disk: %.1f GB free of %.1f GB' % (free / 1e9, total / 1e9))
        sizes = ', '.join('%s %.1f MB' % (esc(n), folder_size(os.path.join(REPOS, n)) / 1e6) for n in repositories())
        return '<section><h2>Health</h2><ul style="margin:0;padding-left:18px">%s</ul><p class="muted">Repositories: %s</p></section>' % (''.join(items), sizes)

    def undo_page(self, state):
        repo = self.query.get('repo', [''])[0]
        try:
            rev = int(self.query.get('rev', [''])[0])
        except ValueError:
            raise Refused('Unknown revision.')
        entry = next((e for e in activity([repo], 200) if e['rev'] == rev), None) if repo in repositories() else None
        if entry is None:
            raise Refused('Unknown submit.')
        described = {'A': 'added → will be removed', 'M': 'changed → previous version restored', 'U': 'changed → previous version restored',
                     'D': 'deleted → restored', 'R': 'replaced → previous version restored'}
        try:
            changes = undo_plan(repo, rev)
            problem = None
        except Refused as exc:
            changes, problem = changed_paths(repo, rev), str(exc)
        rows = ''.join('<tr><td><code>%s</code></td><td class="muted">%s</td></tr>' % (esc(p + ('/' if d else '')), described.get(a, a)) for a, p, d in changes)
        action = ('<p class="bad">%s</p>' % esc(problem)) if problem else (
            '<p>This creates a <b>new</b> revision that puts these files back the way they were before r%d. History is kept, and the undo can itself be undone.</p>%s'
            % (rev, self.form('undo-submit', {'repo': repo, 'rev': str(rev)}, 'Undo r%d' % rev, primary=True)))
        return ('<section><h2>Undo %s r%d</h2><p>%s by <b>%s</b>: %s</p><div class="scroll"><table><tr><th>File</th><th>Undo will</th></tr>%s</table></div>%s'
                '<p><a href="/admin">Back</a></p></section>') % (esc(repo), rev, esc(entry['date']), esc(entry['author']), esc(entry['msg']), rows, action)

    def locks_page(self, state):
        rows = ''
        for name in repositories():
            for lock in locks(name):
                rows += '<tr><td>%s</td><td><code>%s</code></td><td><b>%s</b></td><td class="muted">%s</td><td>%s</td></tr>' % (
                    esc(name), esc(lock['path']), esc(lock.get('owner', '?')), esc(lock.get('created', '')),
                    self.form('release-lock', {'repo': name, 'path': lock['path']}, 'Release',
                              extra='<label class="muted"><input type="checkbox" name="confirmed" value="1" required> they\'re done</label> '))
        return ('<section><h2>Locked files</h2><p><b>Releasing does not keep that student\'s unsubmitted changes on their computer.</b> '
                'Only release a lock when they\'ve confirmed they\'re done, will use Set Aside My Changes to keep a copy, or can\'t Submit '
                '(lost laptop, left the team). Locks never expire by themselves.</p><div class="scroll"><table>'
                '<tr><th>Where</th><th>File</th><th>Locked by</th><th>Since</th><th></th></tr>%s</table></div></section>') % (
                    rows or '<tr><td colspan="5" class="muted">Nothing is locked.</td></tr>')

    def addin_page(self, state):
        current = state.get('addin')
        if current:
            info = ('<p>Published: <b>%s</b> (%s, %.1f MB) — %s</p><p class="muted">SHA-256 <code>%s</code></p>%s') % (
                esc(current['version']), esc(current['file']), current.get('size', 0) / 1048576.0,
                '<span class="bad">required: students must install it before new edits and inserts (they can still Submit work they already have)</span>' if current.get('required')
                else '<span class="ok">optional: students are offered it</span>', esc(current['sha256']),
                self.form('addin-required', {}, 'Make optional' if current.get('required') else 'Make required'))
        else:
            info = '<p class="muted">Nothing published yet. Students keep whatever version they installed.</p>'
        staged = state.get('staged_addin')
        if staged:
            staged_html = ('<p><b>%s</b> from GitHub, staged %s (%.1f MB, SHA-256 verified <code>%s…</code>)</p><div class="row">%s %s %s</div>') % (
                esc(staged['version']), esc(staged.get('at', '')), staged['size'] / 1048576.0, esc(staged['sha256'][:16]),
                self.form('release-staged', {}, 'Release to students', primary=True),
                self.form('release-staged', {'required': '1'}, 'Release as required'),
                self.form('discard-staged', {}, 'Discard'))
        else:
            staged_html = '<p class="muted">Nothing waiting. Push a version tag (for example <code>v0.6.3</code>) and GitHub stages the installer here.</p>'
        upload_form = ('<form method="post" enctype="multipart/form-data" class="row"><input type="hidden" name="token" value="%s">'
                       '<input type="hidden" name="kind" value="addin"><input type="file" name="files" accept=".exe" required>'
                       '<input name="sha256" placeholder="SHA-256 from the GitHub release (recommended)" size="40" pattern="[0-9a-fA-F]{64}" aria-label="Expected SHA-256">'
                       '<label><input type="checkbox" name="required" value="1"> Required</label><button class="primary">Publish</button></form>'
                       '<p class="muted">Download <code>JOCO-ROBOS-CAD-Setup-x.y.z.exe</code> from the '
                       '<a href="https://github.com/Imdad3456/joco-robos-cad/releases">releases page</a> (or build it with '
                       '<code>scripts\\Build-Installer.ps1</code>), and upload it here with the SHA-256 from its release notes. '
                       'Students get a prompt in SOLIDWORKS; after they save and close SOLIDWORKS it installs and reopens. '
                       'Use <b>Required</b> when older add-ins must not start new work (for example after a server or file-format change); '
                       'they can always Submit or Set Aside what they already have.</p>') % self.token()
        beats = read_json(HEARTBEATS) or {}
        recent = {u: b for u, b in beats.items() if (age_hours(b.get('seen')) or 1e9) < 30 * 24}
        if current and recent:
            on = sum(1 for b in recent.values() if version_key(b.get('version', '0.0.0')) >= version_key(current['version']))
            info += '<p>%d of %d students seen in the last 30 days have %s or newer. Details on the Accounts tab.</p>' % (on, len(recent), esc(current['version']))
        approved = state.get('solidworks')
        sw_form = ('<form method="post" class="row"><input type="hidden" name="token" value="%s"><input type="hidden" name="action" value="set-solidworks">'
                   '<input name="year" value="%s" placeholder="e.g. 2026" size="8" pattern="20[0-9][0-9]" aria-label="Approved SOLIDWORKS year">'
                   '<button class="primary">Save</button></form><p class="muted">%s A newer SOLIDWORKS saves files the rest of the team can\'t open, '
                   'so the add-in lets it look but not edit or submit team CAD. Change this only when everyone has upgraded; then a mentor runs '
                   'Tools → JOCO ROBOS CAD → Upgrade Robot Files once. Each student\'s version is on the Accounts tab.</p>') % (
                       self.token(), esc(approved or ''), ('Approved: <b>SOLIDWORKS %s</b>.' % esc(approved)) if approved else '<span class="bad">Not set: any version can edit.</span>')
        return ('<section><h2>Student add-in</h2>%s</section><section><h2>Team SOLIDWORKS version</h2>%s</section><section><h2>Waiting from GitHub</h2>%s</section>'
                '<section><h2>Upload manually</h2>%s</section>') % (info, sw_form, staged_html, upload_form)

    def library_page(self, state):
        parts = files(LIBRARY) if LIBRARY in repositories() else []
        held = {l['path'].lstrip('/'): l.get('owner') for l in (locks(LIBRARY) if LIBRARY in repositories() else [])}
        rows, folder = '', None
        for path in parts:
            parent, _, name = path.rpartition('/')
            if parent != folder:
                folder = parent
                rows += '<tr><td colspan="2"><b>%s</b></td></tr>' % esc(parent or '(top level)')
            rows += '<tr><td>&nbsp;&nbsp;%s</td><td class="muted">%s</td></tr>' % (esc(name), ('🔒 ' + esc(held[path])) if path in held else '')
        folders = sorted({p.rpartition('/')[0] for p in parts if '/' in p} | set(LIBRARY_FOLDERS))
        options = ''.join('<option>%s</option>' % esc(f) for f in folders)
        seasons = [n for n in repositories() if SEASON.match(n)]
        sources = ''.join('<option value="%s|%s">%s — %s</option>' % (esc(s), esc(f), esc(s), esc(f)) for s in reversed(seasons) for f in files(s))
        token = self.token()
        return (('<section><h2>Reusable parts library</h2><p class="muted">Every student has a copy at <code>C:\\JOCO-ROBOS\\Library</code>. '
                '“Insert from Library” copies a part into the robot the first time it is used there. That copy then belongs to the robot: '
                'later library changes never replace it, so mates and geometry can\'t change underneath a design. '
                'Students can also improve library parts with Edit and Submit.</p><div class="scroll"><table><tr><th>Part</th><th></th></tr>%s</table></div></section>'
                '<!--frcdesign--><section><h2>Upload new parts</h2><form method="post" enctype="multipart/form-data" class="row"><input type="hidden" name="token" value="%s">'
                '<input type="file" name="files" multiple accept=".sldprt,.sldasm,.slddrw" required>'
                '<input name="folder" list="folders" value="Hardware" required aria-label="Library folder"><datalist id="folders">%s</datalist>'
                '<input name="comment" placeholder="Comment (optional)" aria-label="Comment"><button class="primary">Upload</button></form>'
                '<p class="muted">Up to 100 MB. For an assembly, upload it together with all of its parts in one go. New folder names are fine.</p></section>'
                '<section><h2>Copy a robot part into the library</h2><form method="post" class="row"><input type="hidden" name="token" value="%s">'
                '<input type="hidden" name="action" value="promote"><select name="choice" required aria-label="Robot file">%s</select>'
                '<input name="folder" list="folders" value="Mechanisms" required aria-label="Library folder"><button class="primary">Add to library</button></form></section>') % (
                    rows or '<tr><td colspan="2" class="muted">Empty so far.</td></tr>', token, options, token, sources or '<option value="">No robot files yet</option>'
                )).replace('<!--frcdesign-->', self.frc_section(), 1)

    def frc_section(self):
        registry = frcdesign._registry()
        imports = registry.get('imports', {}).values()
        ready = sorted((e for e in imports if e.get('status') == 'ready'), key=lambda e: -e.get('completedAt', 0))
        pending = [e for e in imports if e.get('status') == 'importing']
        day = time.strftime('%Y-%m-%d', time.gmtime())
        today = sum(1 for e in registry.get('exports', []) if e.get('day') == day)
        configured = bool(os.environ.get('ONSHAPE_ACCESS_KEY')) and bool(os.environ.get('ONSHAPE_SECRET_KEY'))
        calls = frcdesign.calls_this_year()
        rows = ''.join('<tr><td>%s<div class="muted">%s %s</div></td><td>%s</td><td><code>%s</code></td></tr>' % (
            esc(e['name']), esc(e.get('vendor', '')), esc(e.get('partNumber', '')), esc(e.get('by', '')), esc(e['libraryPath']))
            for e in ready[:15])
        return ('<section><h2>FRCDesignLib imports</h2><p class="muted">Students search FRCDesignLib in SOLIDWORKS; the first person to use a part and '
                'configuration imports it into <code>Library/FRCDesignLib</code>, and everyone after reuses it. Onshape export: %s. '
                'Exports today: %d of %d. Imported so far: %d%s. Onshape API calls this year: <b>%d</b> (imports stop at %d; Onshape allows 2,500).</p><div class="scroll"><table><tr><th>Part</th><th>Imported by</th><th>Library file</th></tr>%s</table></div></section>') % (
                    '<span class="ok">ready</span>' if configured else '<span class="bad">no Onshape key on the server</span>',
                    today, frcdesign.DAILY_EXPORTS, len(ready), (', %d in progress' % len(pending)) if pending else '', calls, frcdesign.ANNUAL_CALLS,
                    rows or '<tr><td colspan="3" class="muted">Nothing imported yet.</td></tr>')

    def users_page(self, state):
        rows = ''
        beats = read_json(HEARTBEATS) or {}
        invites = read_json(INVITES) or {}
        for name in users():
            mentor = name in state['mentors']
            invite = invites.get(name)
            pending = ('<div><b>Setup code: <code style="font-size:15px">%s</code></b> <span class="muted">(expires %s)</span></div>' % (
                esc(invite['code']), time.strftime('%b %d', time.localtime(invite['expires'])))) if invite and invite['expires'] > time.time() else ''
            reset = pending + self.form('reset-password', {'username': name}, 'New setup code')
            tools = '' if name == self.user else (self.form('toggle-mentor', {'username': name}, 'Remove mentor' if mentor else 'Make mentor') + ' ' +
                                                   self.form('delete-user', {'username': name}, 'Delete'))
            beat = beats.get(name) or {}
            hours = age_hours(beat.get('seen'))
            approved = state.get('solidworks')
            sw = beat.get('solidworks')
            sw_html = '' if not sw else ' · <span class="%s">SOLIDWORKS %s</span>' % ('bad' if approved and sw != approved else 'muted', esc(sw))
            seen = '<span class="muted">never</span>' if hours is None else '%s%s · %s%s' % (
                esc(beat.get('version', '?')), sw_html, 'today' if hours < 24 else '%d days ago' % (hours // 24),
                (' · ' + esc(', '.join(beat.get('computers', [])))) if beat.get('computers') else '')
            rows += '<tr><td><b>%s</b> %s</td><td>%s</td><td>%s</td><td>%s</td></tr>' % (esc(name), '<span class="tag">mentor</span>' if mentor else '', seen, reset, tools)
        add = ('<form method="post" class="row"><input type="hidden" name="token" value="%s"><input type="hidden" name="action" value="add-user">'
               '<input name="username" placeholder="username (optional)" pattern="[a-z0-9][a-z0-9._\\-]{1,31}" aria-label="Username (optional)">'

               '<label><input type="checkbox" name="mentor" value="1"> Mentor</label><button class="primary">Make setup code</button></form>'
               '<p class="muted">Leave the username empty and just hand out the one-time code (valid %d days): the student enters it the first time SOLIDWORKS starts '
               'and chooses their own username and password. Type a username to pick it for them instead. Mentors never see passwords. '
               '"New setup code" next to a name resets a forgotten password the same way.</p>') % (self.token(), INVITE_DAYS)
        unused = ''.join('<tr><td><code style="font-size:15px"><b>%s</b></code> %s</td><td>%s</td><td>%s</td><td>%s</td></tr>' % (
            esc(i['code']), '<span class="tag">mentor</span>' if i.get('mentor') else '', esc(i.get('by', '')),
            time.strftime('%b %d', time.localtime(i['expires'])), self.form('cancel-code', {'id': cid}, 'Cancel'))
            for cid, i in open_codes())
        unused = ('<section><h2>Unused setup codes</h2><div class="scroll"><table><tr><th>Code</th><th>Made by</th><th>Expires</th><th></th></tr>%s</table></div></section>' % unused
                  if unused else '')
        waiting = ''.join('<tr><td><b>%s</b></td><td>%s</td><td>%s</td><td><code style="font-size:15px"><b>%s</b></code></td><td>%s</td></tr>' % (
            esc(name), time.strftime('%b %d %H:%M', time.localtime(r['at'])), esc(r.get('address', '')), esc(r['code']),
            self.form('reject-request', {'username': name}, 'Reject'))
            for name, r in sorted(pending_requests().items(), key=lambda kv: kv[1]['at']))
        waiting = ('<section><h2>Students waiting for a code</h2><p class="muted">They asked from SOLIDWORKS with the username and password they chose. '
                   'Give each student the code next to their name (in person, so you know it\'s them); they type it in and their account works. '
                   'Reject anything you don\'t recognize.</p><div class="scroll"><table><tr><th>Username</th><th>Asked</th><th>From</th><th>Code</th><th></th></tr>%s</table></div></section>' % waiting
                   if waiting else '')
        return waiting + ('<section><h2>Add an account</h2>%s</section>%s<section><h2>Accounts</h2><div class="scroll"><table>'
                '<tr><th>User</th><th>Add-in · last seen · computers</th><th>Setup</th><th></th></tr>%s</table></div></section>') % (add, unused, rows)


def serve():
    server = ThreadingHTTPServer(('127.0.0.1', int(os.environ.get('JOCO_ADMIN_PORT', '8092'))), Admin)
    server.serve_forever()


if __name__ == '__main__':
    command = sys.argv[1:2] or ['']
    if command == ['ensure']:
        ensure()
    elif command == ['serve']:
        serve()
    elif command == ['import-season'] and len(sys.argv) in (5, 6):
        # joco.py import-season 2026-Robot /tmp/import imdad ["Clean Robot CAD/2026ASSembly4.SLDASM"]
        with Locked():
            count = import_season(sys.argv[2], sys.argv[3], sys.argv[4], 'Import %s from existing CAD' % sys.argv[2])
            state = load_state()
            if len(sys.argv) == 6:
                state.setdefault('masters', {})[sys.argv[2]] = sys.argv[5]
            if not state.get('active'):
                state['active'] = sys.argv[2]  # A new server's first season: the one students open.
            save_state(state)
        print('Imported and verified %d files into %s.' % (count, sys.argv[2]))
    elif command == ['mentor'] and len(sys.argv) == 4 and sys.argv[2] in ('add', 'remove'):
        with Locked():
            state = load_state()
            if sys.argv[3] not in users():
                sys.exit('Unknown user: ' + sys.argv[3])
            state['mentors'] = sorted((set(state['mentors']) | {sys.argv[3]}) if sys.argv[2] == 'add' else (set(state['mentors']) - {sys.argv[3]}))
            save_state(state)
        print('Mentors: ' + ', '.join(state['mentors']))
    elif command == ['test-season'] and len(sys.argv) in (4, 5) and sys.argv[2] in ('create', 'remove'):
        # joco.py test-season create 2099-Robot 2026-Robot   |   joco.py test-season remove 2099-Robot
        with Locked():
            try:
                if sys.argv[2] == 'create' and len(sys.argv) == 5:
                    print('Created %s as a copy of %s (r%d), without locks. Students pick it with Tools → Choose Robot.' % (
                        sys.argv[3], sys.argv[4], create_test_season(sys.argv[3], sys.argv[4])))
                elif sys.argv[2] == 'remove' and len(sys.argv) == 4:
                    remove_test_season(sys.argv[3])
                    print('Removed test season %s (kept as a .deleted- folder on the server).' % sys.argv[3])
                else:
                    sys.exit('usage: joco.py test-season create NAME FROM | test-season remove NAME')
            except Refused as exc:
                sys.exit(str(exc))
    else:
        sys.exit('usage: joco.py ensure | serve | mentor add|remove USER | test-season create NAME FROM | test-season remove NAME')
