ServerName cad.imdad.stream
<VirtualHost *:80>
    ServerName cad.imdad.stream
    <Location /svn>
        DAV svn
        SVNParentPath /var/lib/svn
        SVNListParentPath Off
        AuthType Basic
        AuthName "JOCO ROBOS CAD"
        AuthUserFile /etc/joco/users
        Require valid-user
    </Location>
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
